<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>为什么在 C# 中捕获并重新抛出异常？ | StackOverflow Snapshot</title>
<link href="../../assets/css/all-nocdn.css" rel="stylesheet" type="text/css">
<meta name="theme-color" content="#5670d4">
<meta name="generator" content="Nikola (getnikola.com)">
<link rel="canonical" href="https://ohstackoverflow.netlify.app/posts/wei-shi-yao-zai-c-zhong-bu-huo-bing-zhong-xin-pao-chu-yi-chang/">
<!--[if lt IE 9]><script src="../../assets/js/html5.js"></script><![endif]--><meta name="author" content="Arya">
<link rel="prev" href="../yaml-yaml-zhong-de-zi-fu-chuan-xu-yao-yin-hao-ma/" title="YAML：YAML 中的字符串需要引号吗？" type="text/html">
<link rel="next" href="../bao-han-zuo-zhe-he-ri-qi-de-git-log-de-zui-duan-shu-chu/" title="包含作者和日期的 git log 的最短输出" type="text/html">
<meta property="og:site_name" content="StackOverflow Snapshot">
<meta property="og:title" content="为什么在 C# 中捕获并重新抛出异常？">
<meta property="og:url" content="https://ohstackoverflow.netlify.app/posts/wei-shi-yao-zai-c-zhong-bu-huo-bing-zhong-xin-pao-chu-yi-chang/">
<meta property="og:description" content="我正在查看文章 C# - 可序列化 DTO 上的数据传输对象 。
文章包括这段代码：
public static string SerializeDTO(DTO dto) {
    try {
        XmlSerializer xmlSer = new XmlSerializer(dto.GetType());
        StringWriter sWriter = new St">
<meta property="og:type" content="article">
<meta property="article:published_time" content="2023-02-17T18:05:56+08:00">
<meta property="article:tag" content="cSharp">
<meta property="article:tag" content="exception">
<meta property="article:tag" content="try-catch">
</head>
<body>
<a href="#content" class="sr-only sr-only-focusable">Skip to main content</a>

<!-- Menubar -->

<nav class="navbar navbar-inverse navbar-static-top"><div class="container">
<!-- This keeps the margins nice -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar" aria-controls="bs-navbar" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="https://ohstackoverflow.netlify.app/">

                <span id="blog-title">StackOverflow Snapshot</span>
            </a>
        </div>
<!-- /.navbar-header -->
        <div class="collapse navbar-collapse" id="bs-navbar" aria-expanded="false">
            <ul class="nav navbar-nav">
<li>
<a href="../../archive.html">Archive</a>
                </li>
<li>
<a href="../../categories/">Tags</a>

                
            </li>
</ul>
<ul class="nav navbar-nav navbar-right">
<div style="display:table;min-height:5rem;min-width:27rem;">
					<div class="input-group" style="display: table-cell;vertical-align: middle;">
						<input id="words" type="text" class="form-control" style="max-width:22rem;" onkeydown="if(event.keyCode==13){btn.click()}"><span class="input-group-btn" style="float:left">
							<button id="btn" class="btn btn-default" type="button" data-toggle="modal" data-target="#myModal">
								<span class="glyphicon glyphicon-search">
							</span></button>
						</span>
					</div>
<!-- /input-group -->
				</div>

				
                
                
                
            </ul>
</div>
<!-- /.navbar-collapse -->
    </div>
<!-- /.container -->
</nav><!-- End of Menubar --><!-- 模态框（Modal） --><div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×
				</button>
				<h4 class="modal-title" id="myModalLabel">
					查找结果
				</h4>
			</div>
			<div class="modal-body">
				<div id="search-count" style="min-height:4rem;">
				查找中，请稍后...
				</div>
				<div id="search-result">
				</div>

				
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">
					关闭
				</button>
			</div>
		</div>
<!-- /.modal-content -->
	</div>
<!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="container" id="content" role="main">
    <div class="body-content">
        <!--Body content-->
        <div class="row">
            
            
<article class="post-text h-entry hentry postpage" itemscope="itemscope" itemtype="http://schema.org/Article"><header><h1 class="p-name entry-title" itemprop="headline name"><a href="." class="u-url">为什么在 C# 中捕获并重新抛出异常？</a></h1>

        <div class="metadata">
            <p class="byline author vcard p-author h-card"><span class="byline-name fn p-name" itemprop="author">
                    <a class="u-url" href="../../authors/arya/">Arya</a>
            </span></p>
            <p class="dateline">
            <a href="." rel="bookmark">
            <time class="published dt-published" datetime="2023-02-17T18:05:56+08:00" itemprop="datePublished" title="2023-02-17 18:05">2023-02-17 18:05</time></a>
            </p>
            

        </div>
        

    </header><div class="e-content entry-content" itemprop="articleBody text">
    <p>我正在查看文章 <em>C# - 可序列化 DTO 上的数据传输对象</em> 。</p>
<p>文章包括这段代码：</p>
<div class="code"><pre class="code literal-block"><span class="nv">public</span><span class="w"> </span><span class="nv">static</span><span class="w"> </span><span class="nv">string</span><span class="w"> </span><span class="nv">SerializeDTO</span><span class="ss">(</span><span class="nv">DTO</span><span class="w"> </span><span class="nv">dto</span><span class="ss">)</span><span class="w"> </span>{
<span class="w">    </span><span class="nv">try</span><span class="w"> </span>{
<span class="w">        </span><span class="nv">XmlSerializer</span><span class="w"> </span><span class="nv">xmlSer</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="nv">new</span><span class="w"> </span><span class="nv">XmlSerializer</span><span class="ss">(</span><span class="nv">dto</span>.<span class="nv">GetType</span><span class="ss">())</span><span class="c1">;</span>
<span class="w">        </span><span class="nv">StringWriter</span><span class="w"> </span><span class="nv">sWriter</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="nv">new</span><span class="w"> </span><span class="nv">StringWriter</span><span class="ss">()</span><span class="c1">;</span>
<span class="w">        </span><span class="nv">xmlSer</span>.<span class="nv">Serialize</span><span class="ss">(</span><span class="nv">sWriter</span>,<span class="w"> </span><span class="nv">dto</span><span class="ss">)</span><span class="c1">;</span>
<span class="w">        </span><span class="k">return</span><span class="w"> </span><span class="nv">sWriter</span>.<span class="nv">ToString</span><span class="ss">()</span><span class="c1">;</span>
<span class="w">    </span>}
<span class="w">    </span><span class="nv">catch</span><span class="ss">(</span><span class="nv">Exception</span><span class="w"> </span><span class="nv">ex</span><span class="ss">)</span><span class="w"> </span>{
<span class="w">        </span><span class="nv">throw</span><span class="w"> </span><span class="nv">ex</span><span class="c1">;</span>
<span class="w">    </span>}
}
</pre></div>

<p>文章的其余部分看起来理智合理（对菜鸟来说），但是 try-catch-throw 抛出 WtfException ......
<strong>这不完全等同于根本不处理异常吗？</strong></p>
<p>因此：</p>
<div class="code"><pre class="code literal-block"><span class="nv">public</span><span class="w"> </span><span class="nv">static</span><span class="w"> </span><span class="nv">string</span><span class="w"> </span><span class="nv">SerializeDTO</span><span class="ss">(</span><span class="nv">DTO</span><span class="w"> </span><span class="nv">dto</span><span class="ss">)</span><span class="w"> </span>{
<span class="w">    </span><span class="nv">XmlSerializer</span><span class="w"> </span><span class="nv">xmlSer</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="nv">new</span><span class="w"> </span><span class="nv">XmlSerializer</span><span class="ss">(</span><span class="nv">dto</span>.<span class="nv">GetType</span><span class="ss">())</span><span class="c1">;</span>
<span class="w">    </span><span class="nv">StringWriter</span><span class="w"> </span><span class="nv">sWriter</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="nv">new</span><span class="w"> </span><span class="nv">StringWriter</span><span class="ss">()</span><span class="c1">;</span>
<span class="w">    </span><span class="nv">xmlSer</span>.<span class="nv">Serialize</span><span class="ss">(</span><span class="nv">sWriter</span>,<span class="w"> </span><span class="nv">dto</span><span class="ss">)</span><span class="c1">;</span>
<span class="w">    </span><span class="k">return</span><span class="w"> </span><span class="nv">sWriter</span>.<span class="nv">ToString</span><span class="ss">()</span><span class="c1">;</span>
}
</pre></div>

<p>还是我遗漏了一些有关 C# 错误处理的基本知识？它与 Java 几乎相同（减去已检查的异常），不是吗？... 也就是说，他们都改进了 C++。</p>
<p>Stack Overflow 问题 <em>重新抛出无参数 catch 和什么都不做之间的区别？</em> 似乎支持我的论点，即 try-catch-throw
是一个空操作。</p>
<hr>
<p><strong>编辑：</strong></p>
<p>只是为将来发现此线程的任何人总结......</p>
<p><strong>不要</strong></p>
<div class="code"><pre class="code literal-block"><span class="nv">try</span><span class="w"> </span>{
<span class="w">    </span><span class="o">//</span><span class="w"> </span><span class="k">Do</span><span class="w"> </span><span class="nv">stuff</span><span class="w"> </span><span class="nv">that</span><span class="w"> </span><span class="nv">might</span><span class="w"> </span><span class="nv">throw</span><span class="w"> </span><span class="nv">an</span><span class="w"> </span><span class="nv">exception</span>
}
<span class="nv">catch</span><span class="w"> </span><span class="ss">(</span><span class="nv">Exception</span><span class="w"> </span><span class="nv">e</span><span class="ss">)</span><span class="w"> </span>{
<span class="w">    </span><span class="nv">throw</span><span class="w"> </span><span class="nv">e</span><span class="c1">; // This destroys the strack trace information!</span>
}
</pre></div>

<p>堆栈跟踪信息对于确定问题的根本原因至关重要！</p>
<p><strong>做</strong></p>
<div class="code"><pre class="code literal-block"><span class="nv">try</span><span class="w"> </span>{
<span class="w">    </span><span class="o">//</span><span class="w"> </span><span class="k">Do</span><span class="w"> </span><span class="nv">stuff</span><span class="w"> </span><span class="nv">that</span><span class="w"> </span><span class="nv">might</span><span class="w"> </span><span class="nv">throw</span><span class="w"> </span><span class="nv">an</span><span class="w"> </span><span class="nv">exception</span>
}
<span class="nv">catch</span><span class="w"> </span><span class="ss">(</span><span class="nv">SqlException</span><span class="w"> </span><span class="nv">e</span><span class="ss">)</span><span class="w"> </span>{
<span class="w">    </span><span class="o">//</span><span class="w"> </span><span class="nv">Log</span><span class="w"> </span><span class="nv">it</span>
<span class="w">    </span><span class="k">if</span><span class="w"> </span><span class="ss">(</span><span class="nv">e</span>.<span class="nv">ErrorCode</span><span class="w"> </span><span class="o">!=</span><span class="w"> </span><span class="nv">NO_ROW_ERROR</span><span class="ss">)</span><span class="w"> </span>{<span class="w"> </span><span class="o">//</span><span class="w"> </span><span class="nv">filter</span><span class="w"> </span><span class="nv">out</span><span class="w"> </span><span class="nv">NoDataFound</span>.
<span class="w">        </span><span class="o">//</span><span class="w"> </span><span class="k">Do</span><span class="w"> </span><span class="nv">special</span><span class="w"> </span><span class="nv">cleanup</span>,<span class="w"> </span><span class="nv">like</span><span class="w"> </span><span class="nv">maybe</span><span class="w"> </span><span class="nv">closing</span><span class="w"> </span><span class="nv">the</span><span class="w"> </span><span class="s2">"dirty"</span><span class="w"> </span><span class="nv">database</span><span class="w"> </span><span class="nv">connection</span>.
<span class="w">        </span><span class="nv">throw</span><span class="c1">; // This preserves the stack trace</span>
<span class="w">    </span>}
}
<span class="nv">catch</span><span class="w"> </span><span class="ss">(</span><span class="nv">IOException</span><span class="w"> </span><span class="nv">e</span><span class="ss">)</span><span class="w"> </span>{
<span class="w">    </span><span class="o">//</span><span class="w"> </span><span class="nv">Log</span><span class="w"> </span><span class="nv">it</span>
<span class="w">    </span><span class="nv">throw</span><span class="c1">;</span>
}
<span class="nv">catch</span><span class="w"> </span><span class="ss">(</span><span class="nv">Exception</span><span class="w"> </span><span class="nv">e</span><span class="ss">)</span><span class="w"> </span>{
<span class="w">    </span><span class="o">//</span><span class="w"> </span><span class="nv">Log</span><span class="w"> </span><span class="nv">it</span>
<span class="w">    </span><span class="nv">throw</span><span class="w"> </span><span class="nv">new</span><span class="w"> </span><span class="nv">DAOException</span><span class="ss">(</span><span class="s2">"Excrement occurred"</span>,<span class="w"> </span><span class="nv">e</span><span class="ss">)</span><span class="c1">; // wrapped &amp; chained exceptions (just like java).</span>
}
<span class="nv">finally</span><span class="w"> </span>{
<span class="w">    </span><span class="o">//</span><span class="w"> </span><span class="nv">Normal</span><span class="w"> </span><span class="nv">clean</span><span class="w"> </span><span class="nv">goes</span><span class="w"> </span><span class="nv">here</span><span class="w"> </span><span class="ss">(</span><span class="nv">like</span><span class="w"> </span><span class="nv">closing</span><span class="w"> </span><span class="nv">open</span><span class="w"> </span><span class="nv">files</span><span class="ss">)</span>.
}
</pre></div>

<p>在不太具体的异常之前捕获更具体的异常（就像 Java）。</p>
<hr>
<p><strong>参考：</strong></p>
<ul>
<li>MSDN - 异常处理</li>
<li>MSDN - try-catch（C# 参考）</li>
</ul>
<p><br><br></p>
<h2>解答</h2>
<p>首先，文章中的代码执行它的方式是邪恶的。<code>throw ex</code>将异常中的调用堆栈重置到此 throw 语句丢失有关异常实际创建位置的信息的位置。</p>
<p>其次，如果你只是像那样抓住并重新投掷，我看不出有什么附加值。<code>throw ex</code>如果没有 try-
catch，上面的代码示例会一样好（或者，考虑到位，甚至更好）。</p>
<p>但是，在某些情况下，您可能想要捕获并重新抛出异常。日志记录可能是其中之一：</p>
<div class="code"><pre class="code literal-block">    try 
    {
        // code that may throw exceptions    
    }
    catch(Exception ex) 
    {
        // add error logging here
        throw;
    }
</pre></div>

<p><br></p>
<h3>更多建议</h3>
<p>不要这样做，</p>
<div class="code"><pre class="code literal-block">try 
{
...
}
catch(Exception ex)
{
   throw ex;
}
</pre></div>

<p>您将丢失堆栈跟踪信息...</p>
<p>要么做，</p>
<div class="code"><pre class="code literal-block">try { ... }
catch { throw; }
</pre></div>

<p>或者</p>
<div class="code"><pre class="code literal-block">try { ... }
catch (Exception ex)
{
    throw new Exception("My Custom Error Message", ex);
}
</pre></div>

<p>您可能想要重新抛出的原因之一是如果您正在处理不同的异常，例如</p>
<div class="code"><pre class="code literal-block"><span class="nv">try</span>
{
<span class="w">   </span>...
}
<span class="nv">catch</span><span class="ss">(</span><span class="nv">SQLException</span><span class="w"> </span><span class="nv">sex</span><span class="ss">)</span>
{
<span class="w">   </span><span class="o">//</span><span class="k">Do</span><span class="w"> </span><span class="nv">Custom</span><span class="w"> </span><span class="nv">Logging</span><span class="w"> </span>
<span class="w">   </span><span class="o">//</span><span class="nv">Don</span><span class="err">'t throw exception - swallow it here</span>
<span class="err">}</span>
<span class="err">catch(OtherException oex)</span>
<span class="err">{</span>
<span class="err">   //Do something else</span>
<span class="err">   throw new WrappedException("Other Exception occured");</span>
<span class="err">}</span>
<span class="err">catch</span>
<span class="err">{</span>
<span class="err">   System.Diagnostics.Debug.WriteLine("Eeep! an error, not to worry, will be handled higher up the call stack");</span>
<span class="err">   throw; //Chuck everything else back up the stack</span>
<span class="err">}</span>
</pre></div>

<p><br><br><a href="../why-catch-and-rethrow-an-exception-in-c/">查看原文</a></p>
    </div>
    <aside class="postpromonav"><nav><ul itemprop="keywords" class="tags">
<li><a class="tag p-category" href="../../categories/csharp/" rel="tag">cSharp</a></li>
            <li><a class="tag p-category" href="../../categories/exception/" rel="tag">exception</a></li>
            <li><a class="tag p-category" href="../../categories/try-catch/" rel="tag">try-catch</a></li>
        </ul>
<ul class="pager hidden-print">
<li class="previous">
                <a href="../yaml-yaml-zhong-de-zi-fu-chuan-xu-yao-yin-hao-ma/" rel="prev" title="YAML：YAML 中的字符串需要引号吗？">Previous post</a>
            </li>
            <li class="next">
                <a href="../bao-han-zuo-zhe-he-ri-qi-de-git-log-de-zui-duan-shu-chu/" rel="next" title="包含作者和日期的 git log 的最短输出">Next post</a>
            </li>
        </ul></nav></aside></article>
</div>
        <!--End of body content-->

        <footer id="footer">
            Contents © 2023         Go to StackOverflow Chinese Site  <a href="http://stackoverflow.ink">StackOverflow-ZH</a>  
            
        </footer>
</div>
</div>


            <script src="../../assets/js/all-nocdn.js"></script><!-- fancy dates --><script>
    moment.locale("en");
    fancydates(0, "YYYY-MM-DD HH:mm");
    </script><!-- end fancy dates --><script>
    baguetteBox.run('div#content', {
        ignoreClass: 'islink',
        captions: function(element) {
            return element.getElementsByTagName('img')[0].alt;
    }});
    </script><script src="../../assets/js/search.js"></script>
</body>
</html>
