<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>“throw”和“throw ex”有区别吗？ | StackOverflow Snapshot</title>
<link href="../../assets/css/all-nocdn.css" rel="stylesheet" type="text/css">
<meta name="theme-color" content="#5670d4">
<meta name="generator" content="Nikola (getnikola.com)">
<link rel="canonical" href="https://ohstackoverflow.netlify.app/posts/throw-he-throw-ex-you-qu-bie-ma/">
<!--[if lt IE 9]><script src="../../assets/js/html5.js"></script><![endif]--><meta name="author" content="Arya">
<link rel="prev" href="../ru-he-qu-xiao-xuan-zhong-dan-xuan-an-niu/" title="如何取消选中单选按钮？" type="text/html">
<link rel="next" href="../ru-he-jiang-shu-ju-zuo-wei-biao-dan-shu-ju-er-bu-shi-qing-qiu-fu-zai-fa-bu/" title="如何将数据作为表单数据而不是请求负载发布？" type="text/html">
<meta property="og:site_name" content="StackOverflow Snapshot">
<meta property="og:title" content="“throw”和“throw ex”有区别吗？">
<meta property="og:url" content="https://ohstackoverflow.netlify.app/posts/throw-he-throw-ex-you-qu-bie-ma/">
<meta property="og:description" content="有一些帖子询问这两者之间的区别。
（为什么我还要提这个……）
但是我的问题在某种程度上是不同的，我在另一种 类似上帝的 错误处理方法中调用“throw ex”。
public class Program {
    public static void Main(string[] args) {
        try {
            // something
        } ca">
<meta property="og:type" content="article">
<meta property="article:published_time" content="2023-02-18T06:17:10+08:00">
<meta property="article:tag" content=".net">
<meta property="article:tag" content="cSharp">
<meta property="article:tag" content="exception">
</head>
<body>
<a href="#content" class="sr-only sr-only-focusable">Skip to main content</a>

<!-- Menubar -->

<nav class="navbar navbar-inverse navbar-static-top"><div class="container">
<!-- This keeps the margins nice -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar" aria-controls="bs-navbar" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="https://ohstackoverflow.netlify.app/">

                <span id="blog-title">StackOverflow Snapshot</span>
            </a>
        </div>
<!-- /.navbar-header -->
        <div class="collapse navbar-collapse" id="bs-navbar" aria-expanded="false">
            <ul class="nav navbar-nav">
<li>
<a href="../../archive.html">Archive</a>
                </li>
<li>
<a href="../../categories/">Tags</a>

                
            </li>
</ul>
<ul class="nav navbar-nav navbar-right">
<div style="display:table;min-height:5rem;min-width:27rem;">
					<div class="input-group" style="display: table-cell;vertical-align: middle;">
						<input id="words" type="text" class="form-control" style="max-width:22rem;" onkeydown="if(event.keyCode==13){btn.click()}"><span class="input-group-btn" style="float:left">
							<button id="btn" class="btn btn-default" type="button" data-toggle="modal" data-target="#myModal">
								<span class="glyphicon glyphicon-search">
							</span></button>
						</span>
					</div>
<!-- /input-group -->
				</div>

				
                
                
                
            </ul>
</div>
<!-- /.navbar-collapse -->
    </div>
<!-- /.container -->
</nav><!-- End of Menubar --><!-- 模态框（Modal） --><div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×
				</button>
				<h4 class="modal-title" id="myModalLabel">
					查找结果
				</h4>
			</div>
			<div class="modal-body">
				<div id="search-count" style="min-height:4rem;">
				查找中，请稍后...
				</div>
				<div id="search-result">
				</div>

				
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">
					关闭
				</button>
			</div>
		</div>
<!-- /.modal-content -->
	</div>
<!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="container" id="content" role="main">
    <div class="body-content">
        <!--Body content-->
        <div class="row">
            
            
<article class="post-text h-entry hentry postpage" itemscope="itemscope" itemtype="http://schema.org/Article"><header><h1 class="p-name entry-title" itemprop="headline name"><a href="." class="u-url">“throw”和“throw ex”有区别吗？</a></h1>

        <div class="metadata">
            <p class="byline author vcard p-author h-card"><span class="byline-name fn p-name" itemprop="author">
                    <a class="u-url" href="../../authors/arya/">Arya</a>
            </span></p>
            <p class="dateline">
            <a href="." rel="bookmark">
            <time class="published dt-published" datetime="2023-02-18T06:17:10+08:00" itemprop="datePublished" title="2023-02-18 06:17">2023-02-18 06:17</time></a>
            </p>
            

        </div>
        

    </header><div class="e-content entry-content" itemprop="articleBody text">
    <p>有一些帖子询问这两者之间的区别。<br>
（为什么我还要提这个……）</p>
<p>但是我的问题在某种程度上是不同的，我在另一种 <em>类似上帝的</em> 错误处理方法中调用“throw ex”。</p>
<div class="code"><pre class="code literal-block"><span class="nv">public</span><span class="w"> </span><span class="nv">class</span><span class="w"> </span><span class="nv">Program</span><span class="w"> </span>{
<span class="w">    </span><span class="nv">public</span><span class="w"> </span><span class="nv">static</span><span class="w"> </span><span class="nv">void</span><span class="w"> </span><span class="nv">Main</span><span class="ss">(</span><span class="nv">string</span>[]<span class="w"> </span><span class="nv">args</span><span class="ss">)</span><span class="w"> </span>{
<span class="w">        </span><span class="nv">try</span><span class="w"> </span>{
<span class="w">            </span><span class="o">//</span><span class="w"> </span><span class="nv">something</span>
<span class="w">        </span>}<span class="w"> </span><span class="nv">catch</span><span class="w"> </span><span class="ss">(</span><span class="nv">Exception</span><span class="w"> </span><span class="nv">ex</span><span class="ss">)</span><span class="w"> </span>{
<span class="w">            </span><span class="nv">HandleException</span><span class="ss">(</span><span class="nv">ex</span><span class="ss">)</span><span class="c1">;</span>
<span class="w">        </span>}
<span class="w">    </span>}

<span class="w">    </span><span class="nv">private</span><span class="w"> </span><span class="nv">static</span><span class="w"> </span><span class="nv">void</span><span class="w"> </span><span class="nv">HandleException</span><span class="ss">(</span><span class="nv">Exception</span><span class="w"> </span><span class="nv">ex</span><span class="ss">)</span><span class="w"> </span>{
<span class="w">        </span><span class="k">if</span><span class="w"> </span><span class="ss">(</span><span class="nv">ex</span><span class="w"> </span><span class="nv">is</span><span class="w"> </span><span class="nv">ThreadAbortException</span><span class="ss">)</span><span class="w"> </span>{
<span class="w">            </span><span class="o">//</span><span class="w"> </span><span class="nv">ignore</span><span class="w"> </span><span class="k">then</span>,
<span class="w">            </span><span class="k">return</span><span class="c1">;</span>
<span class="w">        </span>}
<span class="w">        </span><span class="k">if</span><span class="w"> </span><span class="ss">(</span><span class="nv">ex</span><span class="w"> </span><span class="nv">is</span><span class="w"> </span><span class="nv">ArgumentOutOfRangeException</span><span class="ss">)</span><span class="w"> </span>{<span class="w"> </span>
<span class="w">            </span><span class="o">//</span><span class="w"> </span><span class="nv">Log</span><span class="w"> </span><span class="k">then</span>,
<span class="w">            </span><span class="nv">throw</span><span class="w"> </span><span class="nv">ex</span><span class="c1">;</span>
<span class="w">        </span>}
<span class="w">        </span><span class="k">if</span><span class="w"> </span><span class="ss">(</span><span class="nv">ex</span><span class="w"> </span><span class="nv">is</span><span class="w"> </span><span class="nv">InvalidOperationException</span><span class="ss">)</span><span class="w"> </span>{
<span class="w">            </span><span class="o">//</span><span class="w"> </span><span class="k">Show</span><span class="w"> </span><span class="nv">message</span><span class="w"> </span><span class="k">then</span>,
<span class="w">            </span><span class="nv">throw</span><span class="w"> </span><span class="nv">ex</span><span class="c1">;</span>
<span class="w">        </span>}
<span class="w">        </span><span class="o">//</span><span class="w"> </span><span class="nv">and</span><span class="w"> </span><span class="nv">so</span><span class="w"> </span><span class="nv">on</span>.
<span class="w">    </span>}
}
</pre></div>

<p>如果<code>try &amp; catch</code>在
中使用<code>Main</code>，那么我将使用它<code>throw;</code>来重新抛出错误。但是在上面的简化代码中，所有异常都通过<code>HandleException</code></p>
<p>在内部调用时是否<code>throw ex;</code>与调用具有相同的效果？<code>throw``HandleException</code></p>
<p><br><br></p>
<h2>解答</h2>
<p>是，有一点不同。</p>
<ul>
<li>
<p><code>throw ex</code>重置堆栈跟踪（因此您的错误似乎源自<code>HandleException</code>）</p>
</li>
<li>
<p><code>throw</code>不会-原始罪犯将被保留。</p>
<div class="code"><pre class="code literal-block"> static void Main(string[] args)
</pre></div>

<p>{
     try
     {
         Method2();
     }
     catch (Exception ex)
     {
         Console.Write(ex.StackTrace.ToString());
         Console.ReadKey();
     }
 }</p>
<p>private static void Method2()
 {
     try
     {
         Method1();
     }
     catch (Exception ex)
     {
         //throw ex resets the stack trace Coming from Method 1 and propogates it to the caller(Main)
         throw ex;
     }
 }</p>
<p>private static void Method1()
 {
     try
     {
         throw new Exception("Inside Method1");
     }
     catch (Exception)
     {
         throw;
     }
 }</p>
</li>
</ul>
<p><br></p>
<h3>更多建议</h3>
<p>（我之前发布过，@Marc Gravell 已经纠正了我）</p>
<p>这是差异的演示：</p>
<div class="code"><pre class="code literal-block"><span class="nt">static</span><span class="w"> </span><span class="nt">void</span><span class="w"> </span><span class="nt">Main</span><span class="o">(</span><span class="nt">string</span><span class="cp">[]</span><span class="w"> </span><span class="nt">args</span><span class="o">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="err">try</span><span class="w"> </span><span class="err">{</span>
<span class="w">        </span><span class="err">ThrowException1()</span><span class="p">;</span><span class="w"> </span><span class="err">//</span><span class="w"> </span><span class="err">line</span><span class="w"> </span><span class="err">19</span>
<span class="w">    </span><span class="p">}</span><span class="w"> </span><span class="nt">catch</span><span class="w"> </span><span class="o">(</span><span class="nt">Exception</span><span class="w"> </span><span class="nt">x</span><span class="o">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">        </span><span class="err">Console.WriteLine("Exception</span><span class="w"> </span><span class="err">1:")</span><span class="p">;</span>
<span class="w">        </span><span class="err">Console.WriteLine(x.StackTrace)</span><span class="p">;</span>
<span class="w">    </span><span class="p">}</span>
<span class="w">    </span><span class="nt">try</span><span class="w"> </span><span class="p">{</span>
<span class="w">        </span><span class="err">ThrowException2()</span><span class="p">;</span><span class="w"> </span><span class="err">//</span><span class="w"> </span><span class="err">line</span><span class="w"> </span><span class="err">25</span>
<span class="w">    </span><span class="p">}</span><span class="w"> </span><span class="nt">catch</span><span class="w"> </span><span class="o">(</span><span class="nt">Exception</span><span class="w"> </span><span class="nt">x</span><span class="o">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">        </span><span class="err">Console.WriteLine("Exception</span><span class="w"> </span><span class="err">2:")</span><span class="p">;</span>
<span class="w">        </span><span class="err">Console.WriteLine(x.StackTrace)</span><span class="p">;</span>
<span class="w">    </span><span class="p">}</span>
<span class="err">}</span>

<span class="nt">private</span><span class="w"> </span><span class="nt">static</span><span class="w"> </span><span class="nt">void</span><span class="w"> </span><span class="nt">ThrowException1</span><span class="o">()</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="err">try</span><span class="w"> </span><span class="err">{</span>
<span class="w">        </span><span class="err">DivByZero()</span><span class="p">;</span><span class="w"> </span><span class="err">//</span><span class="w"> </span><span class="err">line</span><span class="w"> </span><span class="err">34</span>
<span class="w">    </span><span class="p">}</span><span class="w"> </span><span class="nt">catch</span><span class="w"> </span><span class="p">{</span>
<span class="w">        </span><span class="err">throw</span><span class="p">;</span><span class="w"> </span><span class="err">//</span><span class="w"> </span><span class="err">line</span><span class="w"> </span><span class="err">36</span>
<span class="w">    </span><span class="p">}</span>
<span class="err">}</span>
<span class="nt">private</span><span class="w"> </span><span class="nt">static</span><span class="w"> </span><span class="nt">void</span><span class="w"> </span><span class="nt">ThrowException2</span><span class="o">()</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="err">try</span><span class="w"> </span><span class="err">{</span>
<span class="w">        </span><span class="err">DivByZero()</span><span class="p">;</span><span class="w"> </span><span class="err">//</span><span class="w"> </span><span class="err">line</span><span class="w"> </span><span class="err">41</span>
<span class="w">    </span><span class="p">}</span><span class="w"> </span><span class="nt">catch</span><span class="w"> </span><span class="o">(</span><span class="nt">Exception</span><span class="w"> </span><span class="nt">ex</span><span class="o">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">        </span><span class="err">throw</span><span class="w"> </span><span class="err">ex</span><span class="p">;</span><span class="w"> </span><span class="err">//</span><span class="w"> </span><span class="err">line</span><span class="w"> </span><span class="err">43</span>
<span class="w">    </span><span class="p">}</span>
<span class="err">}</span>

<span class="nt">private</span><span class="w"> </span><span class="nt">static</span><span class="w"> </span><span class="nt">void</span><span class="w"> </span><span class="nt">DivByZero</span><span class="o">()</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="err">int</span><span class="w"> </span><span class="err">x</span><span class="w"> </span><span class="err">=</span><span class="w"> </span><span class="err">0</span><span class="p">;</span>
<span class="w">    </span><span class="err">int</span><span class="w"> </span><span class="err">y</span><span class="w"> </span><span class="err">=</span><span class="w"> </span><span class="err">1</span><span class="w"> </span><span class="err">/</span><span class="w"> </span><span class="err">x</span><span class="p">;</span><span class="w"> </span><span class="err">//</span><span class="w"> </span><span class="err">line</span><span class="w"> </span><span class="err">49</span>
<span class="p">}</span>
</pre></div>

<p>这是输出：</p>
<div class="code"><pre class="code literal-block">Exception 1:
   at UnitTester.Program.DivByZero() in &lt;snip&gt;\Dev\UnitTester\Program.cs:line 49
   at UnitTester.Program.ThrowException1() in &lt;snip&gt;\Dev\UnitTester\Program.cs:line 36
   at UnitTester.Program.TestExceptions() in &lt;snip&gt;\Dev\UnitTester\Program.cs:line 19

Exception 2:
   at UnitTester.Program.ThrowException2() in &lt;snip&gt;\Dev\UnitTester\Program.cs:line 43
   at UnitTester.Program.TestExceptions() in &lt;snip&gt;\Dev\UnitTester\Program.cs:line 25
</pre></div>

<p>您可以看到，在异常 1 中，堆栈跟踪返回到方法<code>DivByZero()</code>，而在异常 2 中则没有。</p>
<p><code>ThrowException1()</code>不过请注意，和中显示的行号<code>ThrowException2()</code>是语句的行号<code>throw</code>， <strong>而不是</strong> 调用
的行号<code>DivByZero()</code>，现在我稍微考虑了一下，这可能是有道理的......</p>
<h4>发布模式下的输出</h4>
<p>例外一：</p>
<div class="code"><pre class="code literal-block">at ConsoleAppBasics.Program.ThrowException1()
at ConsoleAppBasics.Program.Main(String[] args)
</pre></div>

<p>例外 2：</p>
<div class="code"><pre class="code literal-block">at ConsoleAppBasics.Program.ThrowException2()
at ConsoleAppBasics.Program.Main(String[] args)
</pre></div>

<p>它是否仅在调试模式下维护原始 stackTrace？</p>
<p><br><br><a href="../is-there-a-difference-between-throw-and-throw-ex/">查看原文</a></p>
    </div>
    <aside class="postpromonav"><nav><ul itemprop="keywords" class="tags">
<li><a class="tag p-category" href="../../categories/net/" rel="tag">.net</a></li>
            <li><a class="tag p-category" href="../../categories/csharp/" rel="tag">cSharp</a></li>
            <li><a class="tag p-category" href="../../categories/exception/" rel="tag">exception</a></li>
        </ul>
<ul class="pager hidden-print">
<li class="previous">
                <a href="../ru-he-qu-xiao-xuan-zhong-dan-xuan-an-niu/" rel="prev" title="如何取消选中单选按钮？">Previous post</a>
            </li>
            <li class="next">
                <a href="../ru-he-jiang-shu-ju-zuo-wei-biao-dan-shu-ju-er-bu-shi-qing-qiu-fu-zai-fa-bu/" rel="next" title="如何将数据作为表单数据而不是请求负载发布？">Next post</a>
            </li>
        </ul></nav></aside></article>
</div>
        <!--End of body content-->

        <footer id="footer">
            Contents © 2023         Go to StackOverflow Chinese Site  <a href="http://stackoverflow.ink">StackOverflow-ZH</a>  
            
        </footer>
</div>
</div>


            <script src="../../assets/js/all-nocdn.js"></script><!-- fancy dates --><script>
    moment.locale("en");
    fancydates(0, "YYYY-MM-DD HH:mm");
    </script><!-- end fancy dates --><script>
    baguetteBox.run('div#content', {
        ignoreClass: 'islink',
        captions: function(element) {
            return element.getElementsByTagName('img')[0].alt;
    }});
    </script><script src="../../assets/js/search.js"></script>
</body>
</html>
