<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>在 Python 中手动引发（抛出）异常 | StackOverflow Snapshot</title>
<link href="../../assets/css/all-nocdn.css" rel="stylesheet" type="text/css">
<meta name="theme-color" content="#5670d4">
<meta name="generator" content="Nikola (getnikola.com)">
<link rel="canonical" href="https://ohstackoverflow.netlify.app/posts/zai-python-zhong-shou-dong-yin-fa-pao-chu-yi-chang/">
<!--[if lt IE 9]><script src="../../assets/js/html5.js"></script><![endif]--><meta name="author" content="Arya">
<link rel="prev" href="../ru-he-she-zhi-qing-chu-he-qie-huan-dan-ge-wei/" title="如何设置、清除和切换单个位？" type="text/html">
<link rel="next" href="../shi-fou-you-wei-yi-de-android-she-bei-id/" title="是否有唯一的 Android 设备 ID？" type="text/html">
<meta property="og:site_name" content="StackOverflow Snapshot">
<meta property="og:title" content="在 Python 中手动引发（抛出）异常">
<meta property="og:url" content="https://ohstackoverflow.netlify.app/posts/zai-python-zhong-shou-dong-yin-fa-pao-chu-yi-chang/">
<meta property="og:description" content="我如何在 Python 中引发异常以便稍后可以通过except块捕获？

解答

如何在 Python 中手动抛出/引发异常？

使用语义上适合您的问题的最具体的异常构造函数。
在您的消息中具体说明，例如：
raise ValueError('A very specific bad thing happened.')


不要引发一般异常
避免提出泛型Exception。要捕获它，您必须捕获所有其">
<meta property="og:type" content="article">
<meta property="article:published_time" content="2023-02-16T20:12:48+08:00">
<meta property="article:tag" content="exception">
<meta property="article:tag" content="python">
</head>
<body>
<a href="#content" class="sr-only sr-only-focusable">Skip to main content</a>

<!-- Menubar -->

<nav class="navbar navbar-inverse navbar-static-top"><div class="container">
<!-- This keeps the margins nice -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar" aria-controls="bs-navbar" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="https://ohstackoverflow.netlify.app/">

                <span id="blog-title">StackOverflow Snapshot</span>
            </a>
        </div>
<!-- /.navbar-header -->
        <div class="collapse navbar-collapse" id="bs-navbar" aria-expanded="false">
            <ul class="nav navbar-nav">
<li>
<a href="../../archive.html">Archive</a>
                </li>
<li>
<a href="../../categories/">Tags</a>

                
            </li>
</ul>
<ul class="nav navbar-nav navbar-right">
<div style="display:table;min-height:5rem;min-width:27rem;">
					<div class="input-group" style="display: table-cell;vertical-align: middle;">
						<input id="words" type="text" class="form-control" style="max-width:22rem;" onkeydown="if(event.keyCode==13){btn.click()}"><span class="input-group-btn" style="float:left">
							<button id="btn" class="btn btn-default" type="button" data-toggle="modal" data-target="#myModal">
								<span class="glyphicon glyphicon-search">
							</span></button>
						</span>
					</div>
<!-- /input-group -->
				</div>

				
                
                
                
            </ul>
</div>
<!-- /.navbar-collapse -->
    </div>
<!-- /.container -->
</nav><!-- End of Menubar --><!-- 模态框（Modal） --><div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×
				</button>
				<h4 class="modal-title" id="myModalLabel">
					查找结果
				</h4>
			</div>
			<div class="modal-body">
				<div id="search-count" style="min-height:4rem;">
				查找中，请稍后...
				</div>
				<div id="search-result">
				</div>

				
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">
					关闭
				</button>
			</div>
		</div>
<!-- /.modal-content -->
	</div>
<!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="container" id="content" role="main">
    <div class="body-content">
        <!--Body content-->
        <div class="row">
            
            
<article class="post-text h-entry hentry postpage" itemscope="itemscope" itemtype="http://schema.org/Article"><header><h1 class="p-name entry-title" itemprop="headline name"><a href="." class="u-url">在 Python 中手动引发（抛出）异常</a></h1>

        <div class="metadata">
            <p class="byline author vcard p-author h-card"><span class="byline-name fn p-name" itemprop="author">
                    <a class="u-url" href="../../authors/arya/">Arya</a>
            </span></p>
            <p class="dateline">
            <a href="." rel="bookmark">
            <time class="published dt-published" datetime="2023-02-16T20:12:48+08:00" itemprop="datePublished" title="2023-02-16 20:12">2023-02-16 20:12</time></a>
            </p>
            

        </div>
        

    </header><div class="e-content entry-content" itemprop="articleBody text">
    <p>我如何在 Python 中引发异常以便稍后可以通过<code>except</code>块捕获？</p>
<p><br><br></p>
<h2>解答</h2>
<blockquote>
<h3>如何在 Python 中手动抛出/引发异常？</h3>
</blockquote>
<p>使用语义上适合您的问题的最具体的异常构造函数。</p>
<p>在您的消息中具体说明，例如：</p>
<div class="code"><pre class="code literal-block">raise ValueError('A very specific bad thing happened.')
</pre></div>

<h3>不要引发一般异常</h3>
<p>避免提出泛型<code>Exception</code>。要捕获它，您必须捕获所有其他将它子类化的更具体的异常。</p>
<h4>问题 1：隐藏错误</h4>
<div class="code"><pre class="code literal-block"><span class="nv">raise</span><span class="w"> </span><span class="nv">Exception</span><span class="ss">(</span><span class="s1">'I know Python!'</span><span class="ss">)</span><span class="w"> </span>#<span class="w"> </span><span class="nv">Don</span><span class="err">'t! If you catch, likely to hide bugs.</span>
</pre></div>

<p>例如：</p>
<div class="code"><pre class="code literal-block"><span class="nv">def</span><span class="w"> </span><span class="nv">demo_bad_catch</span><span class="ss">()</span>:
<span class="w">    </span><span class="nv">try</span>:
<span class="w">        </span><span class="nv">raise</span><span class="w"> </span><span class="nv">ValueError</span><span class="ss">(</span><span class="s1">'Represents a hidden bug, do not catch this'</span><span class="ss">)</span>
<span class="w">        </span><span class="nv">raise</span><span class="w"> </span><span class="nv">Exception</span><span class="ss">(</span><span class="s1">'This is the exception you expect to handle'</span><span class="ss">)</span>
<span class="w">    </span><span class="nv">except</span><span class="w"> </span><span class="nv">Exception</span><span class="w"> </span><span class="nv">as</span><span class="w"> </span><span class="nv">error</span>:
<span class="w">        </span><span class="nv">print</span><span class="ss">(</span><span class="s1">'Caught this error: '</span><span class="w"> </span><span class="o">+</span><span class="w"> </span><span class="nv">repr</span><span class="ss">(</span><span class="nv">error</span><span class="ss">))</span>

<span class="o">&gt;&gt;&gt;</span><span class="w"> </span><span class="nv">demo_bad_catch</span><span class="ss">()</span>
<span class="nv">Caught</span><span class="w"> </span><span class="nv">this</span><span class="w"> </span><span class="nv">error</span>:<span class="w"> </span><span class="nv">ValueError</span><span class="ss">(</span><span class="s1">'Represents a hidden bug, do not catch this'</span>,<span class="ss">)</span>
</pre></div>

<h4>问题二：抓不住</h4>
<p>更具体的捕获不会捕获一般异常：</p>
<div class="code"><pre class="code literal-block">def demo_no_catch():
    try:
        raise Exception('general exceptions not caught by specific handling')
    except ValueError as e:
        print('we will not catch exception: Exception')


&gt;&gt;&gt; demo_no_catch()
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
  File "&lt;stdin&gt;", line 3, in demo_no_catch
Exception: general exceptions not caught by specific handling
</pre></div>

<h3>最佳实践：<code>raise</code>声明</h3>
<p>相反，使用语义上适合您的问题的最具体的异常构造函数。</p>
<div class="code"><pre class="code literal-block">raise ValueError('A very specific bad thing happened')
</pre></div>

<p>这也方便地允许将任意数量的参数传递给构造函数：</p>
<div class="code"><pre class="code literal-block">raise ValueError('A very specific bad thing happened', 'foo', 'bar', 'baz')
</pre></div>

<p><code>args</code>这些参数由对象上的属性访问<code>Exception</code>。例如：</p>
<div class="code"><pre class="code literal-block"><span class="k">try</span><span class="o">:</span>
<span class="w">    </span><span class="n">some_code_that_may_raise_our_value_error</span><span class="o">()</span>
<span class="n">except</span><span class="w"> </span><span class="n">ValueError</span><span class="w"> </span><span class="k">as</span><span class="w"> </span><span class="n">err</span><span class="o">:</span>
<span class="w">    </span><span class="n">print</span><span class="o">(</span><span class="n">err</span><span class="o">.</span><span class="na">args</span><span class="o">)</span>
</pre></div>

<p>印刷</p>
<div class="code"><pre class="code literal-block">('message', 'foo', 'bar', 'baz')
</pre></div>

<p><code>message</code>在 Python 2.5 中，添加了一个 actual属性<code>BaseException</code>以鼓励用户将 Exceptions
子类化并停止使用<code>args</code>，但args 的引入<code>message</code>和最初的弃用已被收回。</p>
<h3>最佳实践：<code>except</code>子句</h3>
<p>例如，在 except 子句中时，您可能想要记录发生的特定类型的错误，然后重新引发。在保留堆栈跟踪的同时执行此操作的最佳方法是使用裸 raise
语句。例如：</p>
<div class="code"><pre class="code literal-block"><span class="nv">logger</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="nv">logging</span>.<span class="nv">getLogger</span><span class="ss">(</span><span class="nv">__name__</span><span class="ss">)</span>

<span class="nv">try</span>:
<span class="w">    </span><span class="nv">do_something_in_app_that_breaks_easily</span><span class="ss">()</span>
<span class="nv">except</span><span class="w"> </span><span class="nv">AppError</span><span class="w"> </span><span class="nv">as</span><span class="w"> </span><span class="nv">error</span>:
<span class="w">    </span><span class="nv">logger</span>.<span class="nv">error</span><span class="ss">(</span><span class="nv">error</span><span class="ss">)</span>
<span class="w">    </span><span class="nv">raise</span><span class="w">                 </span>#<span class="w"> </span><span class="nv">just</span><span class="w"> </span><span class="nv">this</span><span class="o">!</span>
<span class="w">    </span>#<span class="w"> </span><span class="nv">raise</span><span class="w"> </span><span class="nv">AppError</span><span class="w">      </span>#<span class="w"> </span><span class="nv">Don</span><span class="s1">'t do this, you'</span><span class="nv">ll</span><span class="w"> </span><span class="nv">lose</span><span class="w"> </span><span class="nv">the</span><span class="w"> </span><span class="nv">stack</span><span class="w"> </span><span class="nv">trace</span><span class="o">!</span>
</pre></div>

<h4>不要修改你的错误......但如果你坚持。</h4>
<p>您可以使用 保留堆栈跟踪（和错误值）<code>sys.exc_info()</code>，但这 <strong>更容易出错</strong> 并且 <strong>在 Python 2 和 3
之间存在兼容性问题</strong> ，更喜欢使用 bare<code>raise</code>来重新引发。</p>
<p>解释一下——<code>sys.exc_info()</code>返回类型、值和回溯。</p>
<div class="code"><pre class="code literal-block">type, value, traceback = sys.exc_info()
</pre></div>

<p>这是 Python 2 中的语法——注意这与 Python 3 不兼容：</p>
<div class="code"><pre class="code literal-block">raise AppError, error, sys.exc_info()[2] # avoid this.
# Equivalently, as error *is* the second object:
raise sys.exc_info()[0], sys.exc_info()[1], sys.exc_info()[2]
</pre></div>

<p>如果你愿意，你可以修改你的新加薪会发生什么 - 例如<code>args</code>为实例设置新的：</p>
<div class="code"><pre class="code literal-block">def error():
    raise ValueError('oops!')

def catch_error_modify_message():
    try:
        error()
    except ValueError:
        error_type, error_instance, traceback = sys.exc_info()
        error_instance.args = (error_instance.args[0] + ' &lt;modification&gt;',)
        raise error_type, error_instance, traceback
</pre></div>

<p>And we have preserved the whole traceback while modifying the args. Note that
this is <strong>not a best practice</strong> and it is <strong>invalid syntax</strong> in Python 3
(making keeping compatibility much harder to work around).</p>
<div class="code"><pre class="code literal-block">&gt;&gt;&gt; catch_error_modify_message()
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
  File "&lt;stdin&gt;", line 3, in catch_error_modify_message
  File "&lt;stdin&gt;", line 2, in error
ValueError: oops! &lt;modification&gt;
</pre></div>

<p>In Python 3:</p>
<div class="code"><pre class="code literal-block">raise error.with_traceback(sys.exc_info()[2])
</pre></div>

<p>Again: avoid manually manipulating tracebacks. It's less efficient and more
error prone. And if you're using threading and <code>sys.exc_info</code> you may even get
the wrong traceback (especially if you're using exception handling for control
flow - which I'd personally tend to avoid.)</p>
<h4>Python 3, Exception chaining</h4>
<p>In Python 3, you can chain Exceptions, which preserve tracebacks:</p>
<div class="code"><pre class="code literal-block">raise RuntimeError('specific message') from error
</pre></div>

<p>Be aware:</p>
<ul>
<li>this <em>does</em> allow changing the error type raised, and</li>
<li>this is <em>not</em> compatible with Python 2.</li>
</ul>
<h4>Deprecated Methods:</h4>
<p>These can easily hide and even get into production code. You want to raise an
exception, and doing them will raise an exception, <strong>but not the one
intended!</strong></p>
<p>Valid in Python 2, but not in Python 3 is the following:</p>
<div class="code"><pre class="code literal-block"><span class="nv">raise</span><span class="w"> </span><span class="nv">ValueError</span>,<span class="w"> </span><span class="s1">'message'</span><span class="w"> </span>#<span class="w"> </span><span class="nv">Don</span><span class="s1">'t do this, it'</span><span class="nv">s</span><span class="w"> </span><span class="nv">deprecated</span><span class="o">!</span>
</pre></div>

<p>Only valid in much older versions of Python (2.4 and lower), you may still see
people raising strings:</p>
<div class="code"><pre class="code literal-block"><span class="nv">raise</span><span class="w"> </span><span class="s1">'message'</span><span class="w"> </span>#<span class="w"> </span><span class="nv">really</span><span class="w"> </span><span class="nv">really</span><span class="w"> </span><span class="nv">wrong</span>.<span class="w"> </span><span class="nv">don</span><span class="err">'t do this.</span>
</pre></div>

<p>In all modern versions, this will actually raise a <code>TypeError</code>, because you're
not raising a <code>BaseException</code> type. If you're not checking for the right
exception and don't have a reviewer that's aware of the issue, it could get
into production.</p>
<h3>Example Usage</h3>
<p>I raise Exceptions to warn consumers of my API if they're using it
incorrectly:</p>
<div class="code"><pre class="code literal-block"><span class="nv">def</span><span class="w"> </span><span class="nv">api_func</span><span class="ss">(</span><span class="nv">foo</span><span class="ss">)</span>:
<span class="w">    </span><span class="s1">'''foo should be either '</span><span class="nv">baz</span><span class="s1">' or '</span><span class="nv">bar</span><span class="s1">'. returns something very useful.'''</span>
<span class="w">    </span><span class="k">if</span><span class="w"> </span><span class="nv">foo</span><span class="w"> </span><span class="nv">not</span><span class="w"> </span><span class="nv">in</span><span class="w"> </span><span class="nv">_ALLOWED_ARGS</span>:
<span class="w">        </span><span class="nv">raise</span><span class="w"> </span><span class="nv">ValueError</span><span class="ss">(</span><span class="s1">'{foo} wrong, use "baz" or "bar"'</span>.<span class="nv">format</span><span class="ss">(</span><span class="nv">foo</span><span class="o">=</span><span class="nv">repr</span><span class="ss">(</span><span class="nv">foo</span><span class="ss">)))</span>
</pre></div>

<h3>Create your own error types when apropos</h3>
<blockquote>
<p><strong>"I want to make an error on purpose, so that it would go into the
except"</strong></p>
</blockquote>
<p>You can create your own error types, if you want to indicate something
specific is wrong with your application, just subclass the appropriate point
in the exception hierarchy:</p>
<div class="code"><pre class="code literal-block"><span class="k">class</span> <span class="n">MyAppLookupError</span>(<span class="n">LookupError</span>):
    <span class="s">'''raise this when there'</span><span class="o">s</span> <span class="n">a</span> <span class="nb">lookup</span> <span class="n">error</span> <span class="k">for</span> <span class="k">my</span> <span class="n">app'''</span>
</pre></div>

<p>and usage:</p>
<div class="code"><pre class="code literal-block"><span class="k">if</span><span class="w"> </span><span class="nv">important_key</span><span class="w"> </span><span class="nv">not</span><span class="w"> </span><span class="nv">in</span><span class="w"> </span><span class="nv">resource_dict</span><span class="w"> </span><span class="nv">and</span><span class="w"> </span><span class="nv">not</span><span class="w"> </span><span class="nv">ok_to_be_missing</span>:
<span class="w">    </span><span class="nv">raise</span><span class="w"> </span><span class="nv">MyAppLookupError</span><span class="ss">(</span><span class="s1">'resource is missing, and that is not ok.'</span><span class="ss">)</span>
</pre></div>

<p><br></p>
<h3>更多建议</h3>
<blockquote>
<p><em><strong>不要这样做</strong></em> 。裸养<code>Exception</code>绝对 <strong>不是</strong> 正确的做法；请参阅Aaron Hall 的出色回答。</p>
</blockquote>
<p>没有比这更 Pythonic 的了：</p>
<div class="code"><pre class="code literal-block">raise Exception("I know Python!")
</pre></div>

<p>替换<code>Exception</code>为您要抛出的特定类型的异常。</p>
<p>如果您需要更多信息，请参阅Python 的raise 语句文档。</p>
<p><br><br><a href="../manually-raising-throwing-an-exception-in-python/">查看原文</a></p>
    </div>
    <aside class="postpromonav"><nav><ul itemprop="keywords" class="tags">
<li><a class="tag p-category" href="../../categories/exception/" rel="tag">exception</a></li>
            <li><a class="tag p-category" href="../../categories/python/" rel="tag">python</a></li>
        </ul>
<ul class="pager hidden-print">
<li class="previous">
                <a href="../ru-he-she-zhi-qing-chu-he-qie-huan-dan-ge-wei/" rel="prev" title="如何设置、清除和切换单个位？">Previous post</a>
            </li>
            <li class="next">
                <a href="../shi-fou-you-wei-yi-de-android-she-bei-id/" rel="next" title="是否有唯一的 Android 设备 ID？">Next post</a>
            </li>
        </ul></nav></aside></article>
</div>
        <!--End of body content-->

        <footer id="footer">
            Contents © 2023         Go to StackOverflow Chinese Site  <a href="http://stackoverflow.ink">StackOverflow-ZH</a>  
            
        </footer>
</div>
</div>


            <script src="../../assets/js/all-nocdn.js"></script><!-- fancy dates --><script>
    moment.locale("en");
    fancydates(0, "YYYY-MM-DD HH:mm");
    </script><!-- end fancy dates --><script>
    baguetteBox.run('div#content', {
        ignoreClass: 'islink',
        captions: function(element) {
            return element.getElementsByTagName('img')[0].alt;
    }});
    </script><script src="../../assets/js/search.js"></script>
</body>
</html>
