<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Node.js Best Practice Exception Handling | StackOverflow Snapshot</title>
<link href="../../assets/css/all-nocdn.css" rel="stylesheet" type="text/css">
<meta name="theme-color" content="#5670d4">
<meta name="generator" content="Nikola (getnikola.com)">
<link rel="canonical" href="https://ohstackoverflow.netlify.app/posts/node-js-best-practice-exception-handling/">
<!--[if lt IE 9]><script src="../../assets/js/html5.js"></script><![endif]--><meta name="author" content="Arya">
<link rel="prev" href="../how-to-get-the-type-of-t-from-a-member-of-a-generic-class-or-method/" title="How to get the type of T from a member of a generic class or method" type="text/html">
<link rel="next" href="../syntax-for-a-single-line-while-loop-in-bash/" title="Syntax for a single-line while loop in Bash" type="text/html">
<meta property="og:site_name" content="StackOverflow Snapshot">
<meta property="og:title" content="Node.js Best Practice Exception Handling">
<meta property="og:url" content="https://ohstackoverflow.netlify.app/posts/node-js-best-practice-exception-handling/">
<meta property="og:description" content="I just started trying out node.js a few days ago. I've realized that the Node
is terminated whenever I have an unhandled exception in my program. This is
different than the normal server container tha">
<meta property="og:type" content="article">
<meta property="article:published_time" content="2023-02-17T12:29:18+08:00">
<meta property="article:tag" content="exception">
<meta property="article:tag" content="node.js">
<meta property="article:tag" content="serverside-javascript">
</head>
<body>
<a href="#content" class="sr-only sr-only-focusable">Skip to main content</a>

<!-- Menubar -->

<nav class="navbar navbar-inverse navbar-static-top"><div class="container">
<!-- This keeps the margins nice -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar" aria-controls="bs-navbar" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="https://ohstackoverflow.netlify.app/">

                <span id="blog-title">StackOverflow Snapshot</span>
            </a>
        </div>
<!-- /.navbar-header -->
        <div class="collapse navbar-collapse" id="bs-navbar" aria-expanded="false">
            <ul class="nav navbar-nav">
<li>
<a href="../../archive.html">Archive</a>
                </li>
<li>
<a href="../../categories/">Tags</a>

                
            </li>
</ul>
<ul class="nav navbar-nav navbar-right">
<div style="display:table;min-height:5rem;min-width:27rem;">
					<div class="input-group" style="display: table-cell;vertical-align: middle;">
						<input id="words" type="text" class="form-control" style="max-width:22rem;" onkeydown="if(event.keyCode==13){btn.click()}"><span class="input-group-btn" style="float:left">
							<button id="btn" class="btn btn-default" type="button" data-toggle="modal" data-target="#myModal">
								<span class="glyphicon glyphicon-search">
							</span></button>
						</span>
					</div>
<!-- /input-group -->
				</div>

				
                
                
                
            </ul>
</div>
<!-- /.navbar-collapse -->
    </div>
<!-- /.container -->
</nav><!-- End of Menubar --><!-- 模态框（Modal） --><div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×
				</button>
				<h4 class="modal-title" id="myModalLabel">
					查找结果
				</h4>
			</div>
			<div class="modal-body">
				<div id="search-count" style="min-height:4rem;">
				查找中，请稍后...
				</div>
				<div id="search-result">
				</div>

				
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">
					关闭
				</button>
			</div>
		</div>
<!-- /.modal-content -->
	</div>
<!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="container" id="content" role="main">
    <div class="body-content">
        <!--Body content-->
        <div class="row">
            
            
<article class="post-text h-entry hentry postpage" itemscope="itemscope" itemtype="http://schema.org/Article"><header><h1 class="p-name entry-title" itemprop="headline name"><a href="." class="u-url">Node.js Best Practice Exception Handling</a></h1>

        <div class="metadata">
            <p class="byline author vcard p-author h-card"><span class="byline-name fn p-name" itemprop="author">
                    <a class="u-url" href="../../authors/arya/">Arya</a>
            </span></p>
            <p class="dateline">
            <a href="." rel="bookmark">
            <time class="published dt-published" datetime="2023-02-17T12:29:18+08:00" itemprop="datePublished" title="2023-02-17 12:29">2023-02-17 12:29</time></a>
            </p>
            

        </div>
        

    </header><div class="e-content entry-content" itemprop="articleBody text">
    <p>I just started trying out node.js a few days ago. I've realized that the Node
is terminated whenever I have an unhandled exception in my program. This is
different than the normal server container that I have been exposed to where
only the Worker Thread dies when unhandled exceptions occur and the container
would still be able to receive the request. This raises a few questions:</p>
<ul>
<li>Is <code>process.on('uncaughtException')</code> the only effective way to guard against it? </li>
<li>Will <code>process.on('uncaughtException')</code> catch the unhandled exception during execution of asynchronous processes as well?</li>
<li>Is there a module that is already built (such as sending email or writing to a file) that I could leverage in the case of uncaught exceptions?</li>
</ul>
<p>I would appreciate any pointer/article that would show me the common best
practices for handling uncaught exceptions in node.js</p>
<p><br><br></p>
<h2>Answer</h2>
<p>Update: Joyent now has their own guide. The following information is more of a
summary:</p>
<h3>Safely "throwing" errors</h3>
<p>Ideally we'd like to avoid uncaught errors as much as possible, as such,
instead of literally throwing the error, we can instead safely "throw" the
error using one of the following methods depending on our code architecture:</p>
<ul>
<li>
<p>For synchronous code, if an error happens, return the error:</p>
<div class="code"><pre class="code literal-block"><span class="c1">// Define divider as a syncrhonous function</span>
</pre></div>

<p>var divideSync = function(x,y) {
    // if error condition?
    if ( y === 0 ) {
        // "throw" the error safely by returning it
        return new Error("Can't divide by zero")
    }
    else {
        // no error occured, continue on
        return x/y
    }
}</p>
<p>// Divide 4/2
var result = divideSync(4,2)
// did an error occur?
if ( result instanceof Error ) {
    // handle the error safely
    console.log('4/2=err', result)
}
else {
    // no error occured, continue on
    console.log('4/2='+result)
}</p>
<p>// Divide 4/0
result = divideSync(4,0)
// did an error occur?
if ( result instanceof Error ) {
    // handle the error safely
    console.log('4/0=err', result)
}
else {
    // no error occured, continue on
    console.log('4/0='+result)
}</p>
</li>
<li>
<p>For callback-based (ie. asynchronous) code, the first argument of the callback is <code>err</code>, if an error happens <code>err</code> is the error, if an error doesn't happen then <code>err</code> is <code>null</code>. Any other arguments follow the <code>err</code> argument:</p>
<div class="code"><pre class="code literal-block"><span class="k">var</span><span class="w"> </span><span class="n">divide</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="n">function</span><span class="p">(</span><span class="n">x</span><span class="p">,</span><span class="n">y</span><span class="p">,</span><span class="n">next</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="o">//</span><span class="w"> </span><span class="k">if</span><span class="w"> </span><span class="n">error</span><span class="w"> </span><span class="n">condition</span><span class="err">?</span>
<span class="k">if</span><span class="w"> </span><span class="p">(</span><span class="w"> </span><span class="n">y</span><span class="w"> </span><span class="o">===</span><span class="w"> </span><span class="mi">0</span><span class="w"> </span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="o">//</span><span class="w"> </span><span class="s2">"throw"</span><span class="w"> </span><span class="n">the</span><span class="w"> </span><span class="n">error</span><span class="w"> </span><span class="n">safely</span><span class="w"> </span><span class="n">by</span><span class="w"> </span><span class="n">calling</span><span class="w"> </span><span class="n">the</span><span class="w"> </span><span class="n">completion</span><span class="w"> </span><span class="n">callback</span>
<span class="w">    </span><span class="o">//</span><span class="w"> </span><span class="n">with</span><span class="w"> </span><span class="n">the</span><span class="w"> </span><span class="n">first</span><span class="w"> </span><span class="n">argument</span><span class="w"> </span><span class="n">being</span><span class="w"> </span><span class="n">the</span><span class="w"> </span><span class="n">error</span>
<span class="w">    </span><span class="n">next</span><span class="p">(</span><span class="n">new</span><span class="w"> </span><span class="n">Error</span><span class="p">(</span><span class="s2">"Can't divide by zero"</span><span class="p">))</span>
<span class="p">}</span>
<span class="k">else</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="o">//</span><span class="w"> </span><span class="n">no</span><span class="w"> </span><span class="n">error</span><span class="w"> </span><span class="n">occured</span><span class="p">,</span><span class="w"> </span><span class="k">continue</span><span class="w"> </span><span class="n">on</span>
<span class="w">    </span><span class="n">next</span><span class="p">(</span><span class="nb nb-Type">null</span><span class="p">,</span><span class="w"> </span><span class="n">x</span><span class="o">/</span><span class="n">y</span><span class="p">)</span>
<span class="p">}</span>
</pre></div>

<p>}</p>
<p>divide(4,2,function(err,result){
    // did an error occur?
    if ( err ) {
        // handle the error safely
        console.log('4/2=err', err)
    }
    else {
        // no error occured, continue on
        console.log('4/2='+result)
    }
})</p>
<p>divide(4,0,function(err,result){
    // did an error occur?
    if ( err ) {
        // handle the error safely
        console.log('4/0=err', err)
    }
    else {
        // no error occured, continue on
        console.log('4/0='+result)
    }
})</p>
</li>
<li>
<p>For eventful code, where the error may happen anywhere, instead of throwing the error, fire the <code>error</code> event instead:</p>
<div class="code"><pre class="code literal-block"><span class="c1">// Definite our Divider Event Emitter</span>
</pre></div>

<p>var events = require('events')
var Divider = function(){
    events.EventEmitter.call(this)
}
require('util').inherits(Divider, events.EventEmitter)</p>
<p>// Add the divide function
Divider.prototype.divide = function(x,y){
    // if error condition?
    if ( y === 0 ) {
        // "throw" the error safely by emitting it
        var err = new Error("Can't divide by zero")
        this.emit('error', err)
    }
    else {
        // no error occured, continue on
        this.emit('divided', x, y, x/y)
    }</p>
<div class="code"><pre class="code literal-block"><span class="c1">// Chain</span>
<span class="k">return</span><span class="w"> </span><span class="n">this</span><span class="p">;</span>
</pre></div>

<p>}</p>
<p>// Create our divider and listen for errors
var divider = new Divider()
divider.on('error', function(err){
    // handle the error safely
    console.log(err)
})
divider.on('divided', function(x,y,result){
    console.log(x+'/'+y+'='+result)
})</p>
<p>// Divide
divider.divide(4,2).divide(4,0)</p>
</li>
</ul>
<h3>Safely "catching" errors</h3>
<p>Sometimes though, there may still be code that throws an error somewhere which
can lead to an uncaught exception and a potential crash of our application if
we don't catch it safely. Depending on our code architecture we can use one of
the following methods to catch it:</p>
<ul>
<li>
<p>When we know where the error is occurring, we can wrap that section in a node.js domain</p>
<div class="code"><pre class="code literal-block"><span class="k">var</span><span class="w"> </span><span class="n">d</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="n">require</span><span class="p">(</span><span class="s1">'domain'</span><span class="p">)</span><span class="o">.</span><span class="n">create</span><span class="p">()</span>
</pre></div>

<p>d.on('error', function(err){
    // handle the error safely
    console.log(err)
})</p>
<p>// catch the uncaught errors in this asynchronous or synchronous code block
d.run(function(){
    // the asynchronous or synchronous code that we want to catch thrown errors on
    var err = new Error('example')
    throw err
})</p>
</li>
<li>
<p>If we know where the error is occurring is synchronous code, and for whatever reason can't use domains (perhaps old version of node), we can use the try catch statement:</p>
<div class="code"><pre class="code literal-block"><span class="c1">// catch the uncaught errors in this synchronous code block</span>
</pre></div>

<p>// try catch statements only work on synchronous code
try {
    // the synchronous code that we want to catch thrown errors on
    var err = new Error('example')
    throw err
} catch (err) {
    // handle the error safely
    console.log(err)
}</p>
</li>
</ul>
<p>However, be careful not to use <code>try...catch</code> in asynchronous code, as an
asynchronously thrown error will not be caught:</p>
<div class="code"><pre class="code literal-block"><span class="w">    </span><span class="n">try</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="n">setTimeout</span><span class="p">(</span><span class="n">function</span><span class="p">(){</span>
<span class="w">        </span><span class="k">var</span><span class="w"> </span><span class="n">err</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="n">new</span><span class="w"> </span><span class="n">Error</span><span class="p">(</span><span class="s1">'example'</span><span class="p">)</span>
<span class="w">        </span><span class="n">throw</span><span class="w"> </span><span class="n">err</span>
<span class="w">    </span><span class="p">},</span><span class="w"> </span><span class="mi">1000</span><span class="p">)</span>
<span class="p">}</span>
<span class="n">catch</span><span class="w"> </span><span class="p">(</span><span class="n">err</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="o">//</span><span class="w"> </span><span class="n">Example</span><span class="w"> </span><span class="n">error</span><span class="w"> </span><span class="n">won</span><span class="s1">'t be caught here... crashing our app</span>
<span class="w">    </span><span class="o">//</span><span class="w"> </span><span class="n">hence</span><span class="w"> </span><span class="n">the</span><span class="w"> </span><span class="n">need</span><span class="w"> </span><span class="k">for</span><span class="w"> </span><span class="n">domains</span>
<span class="p">}</span>
</pre></div>

<p>If you do want to work with <code>try..catch</code> in conjunction with asynchronous
code, when running Node 7.4 or higher you can use <code>async/await</code> natively to
write your asynchronous functions.</p>
<p>Another thing to be careful about with <code>try...catch</code> is the risk of wrapping
your completion callback inside the <code>try</code> statement like so:</p>
<div class="code"><pre class="code literal-block"><span class="w">    </span><span class="k">var</span><span class="w"> </span><span class="n">divide</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="n">function</span><span class="p">(</span><span class="n">x</span><span class="p">,</span><span class="n">y</span><span class="p">,</span><span class="n">next</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="o">//</span><span class="w"> </span><span class="k">if</span><span class="w"> </span><span class="n">error</span><span class="w"> </span><span class="n">condition</span><span class="err">?</span>
<span class="w">    </span><span class="k">if</span><span class="w"> </span><span class="p">(</span><span class="w"> </span><span class="n">y</span><span class="w"> </span><span class="o">===</span><span class="w"> </span><span class="mi">0</span><span class="w"> </span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">        </span><span class="o">//</span><span class="w"> </span><span class="s2">"throw"</span><span class="w"> </span><span class="n">the</span><span class="w"> </span><span class="n">error</span><span class="w"> </span><span class="n">safely</span><span class="w"> </span><span class="n">by</span><span class="w"> </span><span class="n">calling</span><span class="w"> </span><span class="n">the</span><span class="w"> </span><span class="n">completion</span><span class="w"> </span><span class="n">callback</span>
<span class="w">        </span><span class="o">//</span><span class="w"> </span><span class="n">with</span><span class="w"> </span><span class="n">the</span><span class="w"> </span><span class="n">first</span><span class="w"> </span><span class="n">argument</span><span class="w"> </span><span class="n">being</span><span class="w"> </span><span class="n">the</span><span class="w"> </span><span class="n">error</span>
<span class="w">        </span><span class="n">next</span><span class="p">(</span><span class="n">new</span><span class="w"> </span><span class="n">Error</span><span class="p">(</span><span class="s2">"Can't divide by zero"</span><span class="p">))</span>
<span class="w">    </span><span class="p">}</span>
<span class="w">    </span><span class="k">else</span><span class="w"> </span><span class="p">{</span>
<span class="w">        </span><span class="o">//</span><span class="w"> </span><span class="n">no</span><span class="w"> </span><span class="n">error</span><span class="w"> </span><span class="n">occured</span><span class="p">,</span><span class="w"> </span><span class="k">continue</span><span class="w"> </span><span class="n">on</span>
<span class="w">        </span><span class="n">next</span><span class="p">(</span><span class="nb nb-Type">null</span><span class="p">,</span><span class="w"> </span><span class="n">x</span><span class="o">/</span><span class="n">y</span><span class="p">)</span>
<span class="w">    </span><span class="p">}</span>
<span class="p">}</span>

<span class="k">var</span><span class="w"> </span><span class="n">continueElsewhere</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="n">function</span><span class="p">(</span><span class="n">err</span><span class="p">,</span><span class="w"> </span><span class="n">result</span><span class="p">){</span>
<span class="w">        </span><span class="n">throw</span><span class="w"> </span><span class="n">new</span><span class="w"> </span><span class="n">Error</span><span class="p">(</span><span class="s1">'elsewhere has failed'</span><span class="p">)</span>
<span class="p">}</span>

<span class="n">try</span><span class="w"> </span><span class="p">{</span>
<span class="w">        </span><span class="n">divide</span><span class="p">(</span><span class="mi">4</span><span class="p">,</span><span class="w"> </span><span class="mi">2</span><span class="p">,</span><span class="w"> </span><span class="n">continueElsewhere</span><span class="p">)</span>
<span class="w">        </span><span class="o">//</span><span class="w"> </span><span class="o">^</span><span class="w"> </span><span class="n">the</span><span class="w"> </span><span class="n">execution</span><span class="w"> </span><span class="n">of</span><span class="w"> </span><span class="n">divide</span><span class="p">,</span><span class="w"> </span><span class="ow">and</span><span class="w"> </span><span class="n">the</span><span class="w"> </span><span class="n">execution</span><span class="w"> </span><span class="n">of</span><span class="w"> </span>
<span class="w">        </span><span class="o">//</span><span class="w">   </span><span class="n">continueElsewhere</span><span class="w"> </span><span class="n">will</span><span class="w"> </span><span class="n">be</span><span class="w"> </span><span class="n">inside</span><span class="w"> </span><span class="n">the</span><span class="w"> </span><span class="n">try</span><span class="w"> </span><span class="n">statement</span>
<span class="p">}</span>
<span class="n">catch</span><span class="w"> </span><span class="p">(</span><span class="n">err</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">        </span><span class="n">console</span><span class="o">.</span><span class="n">log</span><span class="p">(</span><span class="n">err</span><span class="o">.</span><span class="n">stack</span><span class="p">)</span>
<span class="w">        </span><span class="o">//</span><span class="w"> </span><span class="o">^</span><span class="w"> </span><span class="n">will</span><span class="w"> </span><span class="n">output</span><span class="w"> </span><span class="n">the</span><span class="w"> </span><span class="s2">"unexpected"</span><span class="w"> </span><span class="n">result</span><span class="w"> </span><span class="n">of</span><span class="p">:</span><span class="w"> </span><span class="n">elsewhere</span><span class="w"> </span><span class="n">has</span><span class="w"> </span><span class="n">failed</span>
<span class="p">}</span>
</pre></div>

<p>This gotcha is very easy to do as your code becomes more complex. As such, it
is best to either use domains or to return errors to avoid (1) uncaught
exceptions in asynchronous code (2) the try catch catching execution that you
don't want it to. In languages that allow for proper threading instead of
JavaScript's asynchronous event-machine style, this is less of an issue.</p>
<ul>
<li>
<p>Finally, in the case where an uncaught error happens in a place that wasn't wrapped in a domain or a try catch statement, we can make our application not crash by using the <code>uncaughtException</code> listener (however doing so can put the application in an unknown state):</p>
<div class="code"><pre class="code literal-block"><span class="c1">// catch the uncaught errors that weren't wrapped in a domain or try catch statement</span>
</pre></div>

<p>// do not use this in modules, but only in applications, as otherwise we could have multiple of these bound
process.on('uncaughtException', function(err) {
    // handle the error safely
    console.log(err)
})</p>
<p>// the asynchronous or synchronous code that emits the otherwise uncaught error
var err = new Error('example')
throw err</p>
</li>
</ul>
<p><br></p>
<h3>Suggest</h3>
<p>Following is a summarization and curation from many different sources on this
topic including code example and quotes from selected blog posts. The complete
list of best practices can be found here</p>
<hr>
<h2><strong>Best practices of Node.JS error handling</strong></h2>
<hr>
<h3>Number1: Use promises for async error handling</h3>
<p><strong>TL;DR:</strong> Handling async errors in callback style is probably the fastest way
to hell (a.k.a the pyramid of doom). The best gift you can give to your code
is using instead a reputable promise library which provides much compact and
familiar code syntax like try-catch</p>
<p><strong>Otherwise:</strong> Node.JS callback style, function(err, response), is a promising
way to un-maintainable code due to the mix of error handling with casual code,
excessive nesting and awkward coding patterns</p>
<p><strong>Code example - good</strong></p>
<div class="code"><pre class="code literal-block"><span class="nf">doWork</span><span class="p">()</span>
<span class="na">.then</span><span class="p">(</span><span class="no">doWork</span><span class="p">)</span>
<span class="na">.then</span><span class="p">(</span><span class="no">doError</span><span class="p">)</span>
<span class="na">.then</span><span class="p">(</span><span class="no">doWork</span><span class="p">)</span>
<span class="na">.catch</span><span class="p">(</span><span class="no">errorHandler</span><span class="p">)</span>
<span class="na">.then</span><span class="p">(</span><span class="no">verify</span><span class="p">)</span><span class="c1">;</span>
</pre></div>

<p><strong>code example anti pattern – callback style error handling</strong></p>
<div class="code"><pre class="code literal-block"><span class="nv">getData</span><span class="ss">(</span><span class="nv">someParameter</span>,<span class="w"> </span><span class="nv">function</span><span class="ss">(</span><span class="nv">err</span>,<span class="w"> </span><span class="nb">result</span><span class="ss">)</span>{
<span class="w">    </span><span class="k">if</span><span class="ss">(</span><span class="nv">err</span><span class="w"> </span><span class="o">!=</span><span class="w"> </span><span class="nv">null</span><span class="ss">)</span>
<span class="w">      </span><span class="o">//</span><span class="k">do</span><span class="w"> </span><span class="nv">something</span><span class="w"> </span><span class="nv">like</span><span class="w"> </span><span class="nv">calling</span><span class="w"> </span><span class="nv">the</span><span class="w"> </span><span class="nv">given</span><span class="w"> </span><span class="nv">callback</span><span class="w"> </span><span class="nv">function</span><span class="w"> </span><span class="nv">and</span><span class="w"> </span><span class="nv">pass</span><span class="w"> </span><span class="nv">the</span><span class="w"> </span><span class="nv">error</span>
<span class="w">    </span><span class="nv">getMoreData</span><span class="ss">(</span><span class="nv">a</span>,<span class="w"> </span><span class="nv">function</span><span class="ss">(</span><span class="nv">err</span>,<span class="w"> </span><span class="nb">result</span><span class="ss">)</span>{
<span class="w">          </span><span class="k">if</span><span class="ss">(</span><span class="nv">err</span><span class="w"> </span><span class="o">!=</span><span class="w"> </span><span class="nv">null</span><span class="ss">)</span>
<span class="w">            </span><span class="o">//</span><span class="k">do</span><span class="w"> </span><span class="nv">something</span><span class="w"> </span><span class="nv">like</span><span class="w"> </span><span class="nv">calling</span><span class="w"> </span><span class="nv">the</span><span class="w"> </span><span class="nv">given</span><span class="w"> </span><span class="nv">callback</span><span class="w"> </span><span class="nv">function</span><span class="w"> </span><span class="nv">and</span><span class="w"> </span><span class="nv">pass</span><span class="w"> </span><span class="nv">the</span><span class="w"> </span><span class="nv">error</span>
<span class="w">        </span><span class="nv">getMoreData</span><span class="ss">(</span><span class="nv">b</span>,<span class="w"> </span><span class="nv">function</span><span class="ss">(</span><span class="nv">c</span><span class="ss">)</span>{<span class="w"> </span>
<span class="w">                </span><span class="nv">getMoreData</span><span class="ss">(</span><span class="nv">d</span>,<span class="w"> </span><span class="nv">function</span><span class="ss">(</span><span class="nv">e</span><span class="ss">)</span>{<span class="w"> </span>
<span class="w">                    </span>...
<span class="w">                </span>}<span class="ss">)</span><span class="c1">;</span>
<span class="w">            </span>}<span class="ss">)</span><span class="c1">;</span>
<span class="w">        </span>}<span class="ss">)</span><span class="c1">;</span>
<span class="w">    </span>}<span class="ss">)</span><span class="c1">;</span>
}<span class="ss">)</span><span class="c1">;</span>
</pre></div>

<p><strong>Blog quote: "We have a problem with promises"</strong> (From the blog pouchdb,
ranked 11 for the keywords "Node Promises")</p>
<blockquote>
<p>"…And in fact, callbacks do something even more sinister: they deprive us of
the stack, which is something we usually take for granted in programming
languages. Writing code without a stack is a lot like driving a car without
a brake pedal: you don’t realize how badly you need it, until you reach for
it and it’s not there. <strong>The whole point of promises is to give us back the
language fundamentals we lost when we went async: return, throw, and the
stack. But you have to know how to use promises correctly in order to take
advantage of them.</strong> "</p>
</blockquote>
<hr>
<h3>Number2: Use only the built-in Error object</h3>
<p><strong>TL;DR:</strong> It pretty common to see code that throws errors as string or as a
custom type – this complicates the error handling logic and the
interoperability between modules. Whether you reject a promise, throw
exception or emit error – using Node.JS built-in Error object increases
uniformity and prevents loss of error information</p>
<p><strong>Otherwise:</strong> When executing some module, being uncertain which type of
errors come in return – makes it much harder to reason about the coming
exception and handle it. Even worth, using custom types to describe errors
might lead to loss of critical error information like the stack trace!</p>
<p><strong>Code example - doing it right</strong></p>
<div class="code"><pre class="code literal-block"><span class="w">    </span><span class="o">//</span><span class="n">throwing</span><span class="w"> </span><span class="n">an</span><span class="w"> </span><span class="n">Error</span><span class="w"> </span><span class="n">from</span><span class="w"> </span><span class="n">typical</span><span class="w"> </span><span class="n">function</span><span class="p">,</span><span class="w"> </span><span class="n">whether</span><span class="w"> </span><span class="n">sync</span><span class="w"> </span><span class="ow">or</span><span class="w"> </span><span class="n">async</span>
<span class="w"> </span><span class="k">if</span><span class="p">(</span><span class="o">!</span><span class="n">productToAdd</span><span class="p">)</span>
<span class="w"> </span><span class="n">throw</span><span class="w"> </span><span class="n">new</span><span class="w"> </span><span class="n">Error</span><span class="p">(</span><span class="s2">"How can I add new product when no value provided?"</span><span class="p">);</span>

<span class="o">//</span><span class="s1">'throwing'</span><span class="w"> </span><span class="n">an</span><span class="w"> </span><span class="n">Error</span><span class="w"> </span><span class="n">from</span><span class="w"> </span><span class="n">EventEmitter</span>
<span class="k">const</span><span class="w"> </span><span class="n">myEmitter</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="n">new</span><span class="w"> </span><span class="n">MyEmitter</span><span class="p">();</span>
<span class="n">myEmitter</span><span class="o">.</span><span class="n">emit</span><span class="p">(</span><span class="s1">'error'</span><span class="p">,</span><span class="w"> </span><span class="n">new</span><span class="w"> </span><span class="n">Error</span><span class="p">(</span><span class="s1">'whoops!'</span><span class="p">));</span>

<span class="o">//</span><span class="s1">'throwing'</span><span class="w"> </span><span class="n">an</span><span class="w"> </span><span class="n">Error</span><span class="w"> </span><span class="n">from</span><span class="w"> </span><span class="n">a</span><span class="w"> </span><span class="n">Promise</span>
<span class="w"> </span><span class="k">return</span><span class="w"> </span><span class="n">new</span><span class="w"> </span><span class="n">promise</span><span class="p">(</span><span class="n">function</span><span class="w"> </span><span class="p">(</span><span class="n">resolve</span><span class="p">,</span><span class="w"> </span><span class="n">reject</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w"> </span><span class="n">DAL</span><span class="o">.</span><span class="n">getProduct</span><span class="p">(</span><span class="n">productToAdd</span><span class="o">.</span><span class="n">id</span><span class="p">)</span><span class="o">.</span><span class="n">then</span><span class="p">((</span><span class="n">existingProduct</span><span class="p">)</span><span class="w"> </span><span class="o">=&gt;</span><span class="p">{</span>
<span class="w"> </span><span class="k">if</span><span class="p">(</span><span class="n">existingProduct</span><span class="w"> </span><span class="o">!=</span><span class="w"> </span><span class="nb nb-Type">null</span><span class="p">)</span>
<span class="w"> </span><span class="k">return</span><span class="w"> </span><span class="n">reject</span><span class="p">(</span><span class="n">new</span><span class="w"> </span><span class="n">Error</span><span class="p">(</span><span class="s2">"Why fooling us and trying to add an existing product?"</span><span class="p">));</span>
</pre></div>

<p><strong>code example anti pattern</strong></p>
<div class="code"><pre class="code literal-block"><span class="c1">//throwing a String lacks any stack trace information and other important properties</span>
<span class="k">if</span><span class="p">(</span>!<span class="n">productToAdd</span><span class="p">)</span>
<span class="w">    </span><span class="n">throw</span><span class="w"> </span><span class="p">(</span><span class="s">"How can I add new product when no value provided?"</span><span class="p">);</span>
</pre></div>

<p><strong>Blog quote: "A string is not an error"</strong> (From the blog devthought, ranked 6
for the keywords “Node.JS error object”)</p>
<blockquote>
<p><strong>"…passing a string instead of an error results in reduced interoperability
between modules. It breaks contracts with APIs that might be performing
instanceof Error checks, or that want to know more about the error</strong>. Error
objects, as we’ll see, have very interesting properties in modern JavaScript
engines besides holding the message passed to the constructor.."</p>
</blockquote>
<hr>
<h3>Number3: Distinguish operational vs programmer errors</h3>
<p><strong>TL;DR:</strong> Operations errors (e.g. API received an invalid input) refer to
known cases where the error impact is fully understood and can be handled
thoughtfully. On the other hand, programmer error (e.g. trying to read
undefined variable) refers to unknown code failures that dictate to gracefully
restart the application</p>
<p><strong>Otherwise:</strong> You may always restart the application when an error appear,
but why letting ~5000 online users down because of a minor and predicted error
(operational error)? the opposite is also not ideal – keeping the application
up when unknown issue (programmer error) occurred might lead unpredicted
behavior. Differentiating the two allows acting tactfully and applying a
balanced approach based on the given context</p>
<p><strong>Code example - doing it right</strong></p>
<div class="code"><pre class="code literal-block"><span class="w">    </span><span class="o">//</span><span class="n">throwing</span><span class="w"> </span><span class="n">an</span><span class="w"> </span><span class="n">Error</span><span class="w"> </span><span class="n">from</span><span class="w"> </span><span class="n">typical</span><span class="w"> </span><span class="n">function</span><span class="p">,</span><span class="w"> </span><span class="n">whether</span><span class="w"> </span><span class="n">sync</span><span class="w"> </span><span class="ow">or</span><span class="w"> </span><span class="n">async</span>
<span class="w"> </span><span class="k">if</span><span class="p">(</span><span class="o">!</span><span class="n">productToAdd</span><span class="p">)</span>
<span class="w"> </span><span class="n">throw</span><span class="w"> </span><span class="n">new</span><span class="w"> </span><span class="n">Error</span><span class="p">(</span><span class="s2">"How can I add new product when no value provided?"</span><span class="p">);</span>

<span class="o">//</span><span class="s1">'throwing'</span><span class="w"> </span><span class="n">an</span><span class="w"> </span><span class="n">Error</span><span class="w"> </span><span class="n">from</span><span class="w"> </span><span class="n">EventEmitter</span>
<span class="k">const</span><span class="w"> </span><span class="n">myEmitter</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="n">new</span><span class="w"> </span><span class="n">MyEmitter</span><span class="p">();</span>
<span class="n">myEmitter</span><span class="o">.</span><span class="n">emit</span><span class="p">(</span><span class="s1">'error'</span><span class="p">,</span><span class="w"> </span><span class="n">new</span><span class="w"> </span><span class="n">Error</span><span class="p">(</span><span class="s1">'whoops!'</span><span class="p">));</span>

<span class="o">//</span><span class="s1">'throwing'</span><span class="w"> </span><span class="n">an</span><span class="w"> </span><span class="n">Error</span><span class="w"> </span><span class="n">from</span><span class="w"> </span><span class="n">a</span><span class="w"> </span><span class="n">Promise</span>
<span class="w"> </span><span class="k">return</span><span class="w"> </span><span class="n">new</span><span class="w"> </span><span class="n">promise</span><span class="p">(</span><span class="n">function</span><span class="w"> </span><span class="p">(</span><span class="n">resolve</span><span class="p">,</span><span class="w"> </span><span class="n">reject</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w"> </span><span class="n">DAL</span><span class="o">.</span><span class="n">getProduct</span><span class="p">(</span><span class="n">productToAdd</span><span class="o">.</span><span class="n">id</span><span class="p">)</span><span class="o">.</span><span class="n">then</span><span class="p">((</span><span class="n">existingProduct</span><span class="p">)</span><span class="w"> </span><span class="o">=&gt;</span><span class="p">{</span>
<span class="w"> </span><span class="k">if</span><span class="p">(</span><span class="n">existingProduct</span><span class="w"> </span><span class="o">!=</span><span class="w"> </span><span class="nb nb-Type">null</span><span class="p">)</span>
<span class="w"> </span><span class="k">return</span><span class="w"> </span><span class="n">reject</span><span class="p">(</span><span class="n">new</span><span class="w"> </span><span class="n">Error</span><span class="p">(</span><span class="s2">"Why fooling us and trying to add an existing product?"</span><span class="p">));</span>
</pre></div>

<p><strong>code example - marking an error as operational (trusted)</strong></p>
<div class="code"><pre class="code literal-block"><span class="o">//</span><span class="n">marking</span><span class="w"> </span><span class="n">an</span><span class="w"> </span><span class="n">error</span><span class="w"> </span><span class="n">object</span><span class="w"> </span><span class="k">as</span><span class="w"> </span><span class="n">operational</span><span class="w"> </span>
<span class="k">var</span><span class="w"> </span><span class="n">myError</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="n">new</span><span class="w"> </span><span class="n">Error</span><span class="p">(</span><span class="s2">"How can I add new product when no value provided?"</span><span class="p">);</span>
<span class="n">myError</span><span class="o">.</span><span class="n">isOperational</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="bp">true</span><span class="p">;</span>

<span class="o">//</span><span class="ow">or</span><span class="w"> </span><span class="k">if</span><span class="w"> </span><span class="n">you</span><span class="s1">'re using some centralized error factory (see other examples at the bullet "Use only the built-in Error object")</span>
<span class="n">function</span><span class="w"> </span><span class="n">appError</span><span class="p">(</span><span class="n">commonType</span><span class="p">,</span><span class="w"> </span><span class="n">description</span><span class="p">,</span><span class="w"> </span><span class="n">isOperational</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="n">Error</span><span class="o">.</span><span class="n">call</span><span class="p">(</span><span class="n">this</span><span class="p">);</span>
<span class="w">    </span><span class="n">Error</span><span class="o">.</span><span class="n">captureStackTrace</span><span class="p">(</span><span class="n">this</span><span class="p">);</span>
<span class="w">    </span><span class="n">this</span><span class="o">.</span><span class="n">commonType</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="n">commonType</span><span class="p">;</span>
<span class="w">    </span><span class="n">this</span><span class="o">.</span><span class="n">description</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="n">description</span><span class="p">;</span>
<span class="w">    </span><span class="n">this</span><span class="o">.</span><span class="n">isOperational</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="n">isOperational</span><span class="p">;</span>
<span class="p">};</span>

<span class="n">throw</span><span class="w"> </span><span class="n">new</span><span class="w"> </span><span class="n">appError</span><span class="p">(</span><span class="n">errorManagement</span><span class="o">.</span><span class="n">commonErrors</span><span class="o">.</span><span class="n">InvalidInput</span><span class="p">,</span><span class="w"> </span><span class="s2">"Describe here what happened"</span><span class="p">,</span><span class="w"> </span><span class="bp">true</span><span class="p">);</span>

<span class="o">//</span><span class="n">error</span><span class="w"> </span><span class="n">handling</span><span class="w"> </span><span class="n">code</span><span class="w"> </span><span class="n">within</span><span class="w"> </span><span class="n">middleware</span>
<span class="n">process</span><span class="o">.</span><span class="n">on</span><span class="p">(</span><span class="s1">'uncaughtException'</span><span class="p">,</span><span class="w"> </span><span class="n">function</span><span class="p">(</span><span class="n">error</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="k">if</span><span class="p">(</span><span class="o">!</span><span class="n">error</span><span class="o">.</span><span class="n">isOperational</span><span class="p">)</span>
<span class="w">        </span><span class="n">process</span><span class="o">.</span><span class="n">exit</span><span class="p">(</span><span class="mi">1</span><span class="p">);</span>
<span class="p">});</span>
</pre></div>

<p><strong>Blog Quote</strong> : "Otherwise you risk the state" (From the blog debugable,
ranked 3 for the keywords "Node.JS uncaught exception")</p>
<blockquote>
<p>" <strong>…By the very nature of how throw works in JavaScript, there is almost
never any way to safely “pick up where you left off”, without leaking
references, or creating some other sort of undefined brittle state. The
safest way to respond to a thrown error is to shut down the process</strong>. Of
course, in a normal web server, you might have many connections open, and it
is not reasonable to abruptly shut those down because an error was triggered
by someone else. The better approach is to send an error response to the
request that triggered the error, while letting the others finish in their
normal time, and stop listening for new requests in that worker"</p>
</blockquote>
<hr>
<h3>Number4: Handle errors centrally, through but not within middleware</h3>
<p><strong>TL;DR:</strong> Error handling logic such as mail to admin and logging should be
encapsulated in a dedicated and centralized object that all end-points (e.g.
Express middleware, cron jobs, unit-testing) call when an error comes in.</p>
<p><strong>Otherwise:</strong> Not handling errors within a single place will lead to code
duplication and probably to errors that are handled improperly</p>
<p><strong>Code example - a typical error flow</strong></p>
<div class="code"><pre class="code literal-block"><span class="c1">//DAL layer, we don't handle errors here</span>
<span class="n">DB</span><span class="p">.</span><span class="n">addDocument</span><span class="p">(</span><span class="n">newCustomer</span><span class="p">,</span><span class="w"> </span><span class="p">(</span><span class="nb">error</span><span class="p">,</span><span class="w"> </span><span class="n">result</span><span class="p">)</span><span class="w"> </span><span class="p">=</span><span class="o">&gt;</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="k">if</span><span class="w"> </span><span class="p">(</span><span class="nb">error</span><span class="p">)</span>
<span class="w">        </span><span class="n">throw</span><span class="w"> </span><span class="n">new</span><span class="w"> </span><span class="n">Error</span><span class="p">(</span><span class="s">"Great error explanation comes here"</span><span class="p">,</span><span class="w"> </span><span class="n">other</span><span class="w"> </span><span class="n">useful</span><span class="w"> </span><span class="n">parameters</span><span class="p">)</span>
<span class="p">});</span>

<span class="c1">//API route code, we catch both sync and async errors and forward to the middleware</span>
<span class="k">try</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="n">customerService</span><span class="p">.</span><span class="n">addNew</span><span class="p">(</span><span class="n">req</span><span class="p">.</span><span class="n">body</span><span class="p">).</span><span class="nb">then</span><span class="p">(</span><span class="k">function</span><span class="w"> </span><span class="p">(</span><span class="n">result</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">        </span><span class="n">res</span><span class="p">.</span><span class="n">status</span><span class="p">(</span><span class="mi">200</span><span class="p">).</span><span class="n">json</span><span class="p">(</span><span class="n">result</span><span class="p">);</span>
<span class="w">    </span><span class="p">}).</span><span class="k">catch</span><span class="p">((</span><span class="nb">error</span><span class="p">)</span><span class="w"> </span><span class="p">=</span><span class="o">&gt;</span><span class="w"> </span><span class="p">{</span>
<span class="w">        </span><span class="n">next</span><span class="p">(</span><span class="nb">error</span><span class="p">)</span>
<span class="w">    </span><span class="p">});</span>
<span class="p">}</span>
<span class="k">catch</span><span class="w"> </span><span class="p">(</span><span class="nb">error</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="n">next</span><span class="p">(</span><span class="nb">error</span><span class="p">);</span>
<span class="p">}</span>

<span class="c1">//Error handling middleware, we delegate the handling to the centrzlied error handler</span>
<span class="n">app</span><span class="p">.</span><span class="n">use</span><span class="p">(</span><span class="k">function</span><span class="w"> </span><span class="p">(</span><span class="n">err</span><span class="p">,</span><span class="w"> </span><span class="n">req</span><span class="p">,</span><span class="w"> </span><span class="n">res</span><span class="p">,</span><span class="w"> </span><span class="n">next</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="n">errorHandler</span><span class="p">.</span><span class="n">handleError</span><span class="p">(</span><span class="n">err</span><span class="p">).</span><span class="nb">then</span><span class="p">((</span><span class="n">isOperationalError</span><span class="p">)</span><span class="w"> </span><span class="p">=</span><span class="o">&gt;</span><span class="w"> </span><span class="p">{</span>
<span class="w">        </span><span class="k">if</span><span class="w"> </span><span class="p">(</span>!<span class="n">isOperationalError</span><span class="p">)</span>
<span class="w">            </span><span class="n">next</span><span class="p">(</span><span class="n">err</span><span class="p">);</span>
<span class="w">    </span><span class="p">});</span>
<span class="p">});</span>
</pre></div>

<p><strong>Blog quote:</strong> "Sometimes lower levels can’t do anything useful except
propagate the error to their caller" (From the blog Joyent, ranked 1 for the
keywords “Node.JS error handling”)</p>
<blockquote>
<p>"…You may end up handling the same error at several levels of the stack.
This happens when lower levels can’t do anything useful except propagate the
error to their caller, which propagates the error to its caller, and so on.
Often, only the top-level caller knows what the appropriate response is,
whether that’s to retry the operation, report an error to the user, or
something else. But that doesn’t mean you should try to report all errors to
a single top-level callback, because that callback itself can’t know in what
context the error occurred"</p>
</blockquote>
<hr>
<h3>Number5: Document API errors using Swagger</h3>
<p><strong>TL;DR:</strong> Let your API callers know which errors might come in return so they
can handle these thoughtfully without crashing. This is usually done with REST
API documentation frameworks like Swagger</p>
<p><strong>Otherwise:</strong> An API client might decide to crash and restart only because he
received back an error he couldn’t understand. Note: the caller of your API
might be you (very typical in a microservices environment)</p>
<p><strong>Blog quote:</strong> "You have to tell your callers what errors can happen" (From
the blog Joyent, ranked 1 for the keywords “Node.JS logging”)</p>
<blockquote>
<p>…We’ve talked about how to handle errors, but when you’re writing a new
function, how do you deliver errors to the code that called your function?
…If you don’t know what errors can happen or don’t know what they mean, then
your program cannot be correct except by accident. So if you’re writing a
new function, you have to tell your callers what errors can happen and what
they mea</p>
</blockquote>
<hr>
<h3>Number6: Shut the process gracefully when a stranger comes to town</h3>
<p><strong>TL;DR:</strong> When an unknown error occurs (a developer error, see best practice
number #3)- there is uncertainty about the application healthiness. A common
practice suggests restarting the process carefully using a ‘restarter’ tool
like Forever and PM2</p>
<p><strong>Otherwise:</strong> When an unfamiliar exception is caught, some object might be in
a faulty state (e.g an event emitter which is used globally and not firing
events anymore due to some internal failure) and all future requests might
fail or behave crazily</p>
<p><strong>Code example - deciding whether to crash</strong></p>
<div class="code"><pre class="code literal-block"><span class="c1">//deciding whether to crash when an uncaught exception arrives</span>
<span class="c1">//Assuming developers mark known operational errors with error.isOperational=true, read best practice #3</span>
<span class="n">process</span><span class="p">.</span><span class="n">on</span><span class="p">(</span><span class="s">'uncaughtException'</span><span class="p">,</span><span class="w"> </span><span class="k">function</span><span class="p">(</span><span class="nb">error</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w"> </span><span class="n">errorManagement</span><span class="p">.</span><span class="n">handler</span><span class="p">.</span><span class="n">handleError</span><span class="p">(</span><span class="nb">error</span><span class="p">);</span>
<span class="w"> </span><span class="k">if</span><span class="p">(</span>!<span class="n">errorManagement</span><span class="p">.</span><span class="n">handler</span><span class="p">.</span><span class="n">isTrustedError</span><span class="p">(</span><span class="nb">error</span><span class="p">))</span>
<span class="w"> </span><span class="n">process</span><span class="p">.</span><span class="nb">exit</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>
<span class="p">});</span>


<span class="c1">//centralized error handler encapsulates error-handling related logic </span>
<span class="k">function</span><span class="w"> </span><span class="nf">errorHandler</span><span class="p">(){</span>
<span class="w"> </span><span class="n">this</span><span class="p">.</span><span class="n">handleError</span><span class="w"> </span><span class="p">=</span><span class="w"> </span><span class="k">function</span><span class="w"> </span><span class="p">(</span><span class="nb">error</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w"> </span><span class="k">return</span><span class="w"> </span><span class="n">logger</span><span class="p">.</span><span class="n">logError</span><span class="p">(</span><span class="n">err</span><span class="p">).</span><span class="nb">then</span><span class="p">(</span><span class="n">sendMailToAdminIfCritical</span><span class="p">).</span><span class="nb">then</span><span class="p">(</span><span class="n">saveInOpsQueueIfCritical</span><span class="p">).</span><span class="nb">then</span><span class="p">(</span><span class="n">determineIfOperationalError</span><span class="p">);</span>
<span class="w"> </span><span class="p">}</span>

<span class="w"> </span><span class="n">this</span><span class="p">.</span><span class="n">isTrustedError</span><span class="w"> </span><span class="p">=</span><span class="w"> </span><span class="k">function</span><span class="p">(</span><span class="nb">error</span><span class="p">)</span>
<span class="w"> </span><span class="p">{</span>
<span class="w"> </span><span class="k">return</span><span class="w"> </span><span class="nb">error</span><span class="p">.</span><span class="n">isOperational</span><span class="p">;</span>
<span class="w"> </span><span class="p">}</span>
</pre></div>

<p><strong>Blog quote:</strong> "There are three schools of thoughts on error handling" (From
the blog jsrecipes)</p>
<blockquote>
<p>…There are primarily three schools of thoughts on error handling: 1. Let the
application crash and restart it. 2. Handle all possible errors and never
crash. <strong>3. Balanced approach between the two</strong></p>
</blockquote>
<hr>
<h3>Number7: Use a mature logger to increase errors visibility</h3>
<p><strong>TL;DR:</strong> A set of mature logging tools like Winston, Bunyan or Log4J, will
speed-up error discovery and understanding. So forget about console.log.</p>
<p><strong>Otherwise:</strong> Skimming through console.logs or manually through messy text
file without querying tools or a decent log viewer might keep you busy at work
until late</p>
<p><strong>Code example - Winston logger in action</strong></p>
<div class="code"><pre class="code literal-block"><span class="o">//</span><span class="n">your</span><span class="w"> </span><span class="n">centralized</span><span class="w"> </span><span class="n">logger</span><span class="w"> </span><span class="n">object</span>
<span class="k">var</span><span class="w"> </span><span class="n">logger</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="n">new</span><span class="w"> </span><span class="n">winston</span><span class="o">.</span><span class="n">Logger</span><span class="p">({</span>
<span class="w"> </span><span class="n">level</span><span class="p">:</span><span class="w"> </span><span class="s1">'info'</span><span class="p">,</span>
<span class="w"> </span><span class="n">transports</span><span class="p">:</span><span class="w"> </span><span class="p">[</span>
<span class="w"> </span><span class="n">new</span><span class="w"> </span><span class="p">(</span><span class="n">winston</span><span class="o">.</span><span class="n">transports</span><span class="o">.</span><span class="n">Console</span><span class="p">)(),</span>
<span class="w"> </span><span class="n">new</span><span class="w"> </span><span class="p">(</span><span class="n">winston</span><span class="o">.</span><span class="n">transports</span><span class="o">.</span><span class="n">File</span><span class="p">)({</span><span class="w"> </span><span class="n">filename</span><span class="p">:</span><span class="w"> </span><span class="s1">'somefile.log'</span><span class="w"> </span><span class="p">})</span>
<span class="w"> </span><span class="p">]</span>
<span class="w"> </span><span class="p">});</span>

<span class="o">//</span><span class="n">custom</span><span class="w"> </span><span class="n">code</span><span class="w"> </span><span class="n">somewhere</span><span class="w"> </span><span class="n">using</span><span class="w"> </span><span class="n">the</span><span class="w"> </span><span class="n">logger</span>
<span class="n">logger</span><span class="o">.</span><span class="n">log</span><span class="p">(</span><span class="s1">'info'</span><span class="p">,</span><span class="w"> </span><span class="s1">'Test Log Message with some parameter </span><span class="si">%s</span><span class="s1">'</span><span class="p">,</span><span class="w"> </span><span class="s1">'some parameter'</span><span class="p">,</span><span class="w"> </span><span class="p">{</span><span class="w"> </span><span class="n">anything</span><span class="p">:</span><span class="w"> </span><span class="s1">'This is metadata'</span><span class="w"> </span><span class="p">});</span>
</pre></div>

<p><strong>Blog quote:</strong> "Lets identify a few requirements (for a logger):" (From the
blog strongblog)</p>
<blockquote>
<p>…Lets identify a few requirements (for a logger): 1. Time stamp each log
line. This one is pretty self explanatory – you should be able to tell when
each log entry occured. 2. Logging format should be easily digestible by
humans as well as machines. 3. Allows for multiple configurable destination
streams. For example, you might be writing trace logs to one file but when
an error is encountered, write to the same file, then into error file and
send an email at the same time…</p>
</blockquote>
<hr>
<h3>Number8: Discover errors and downtime using APM products</h3>
<p><strong>TL;DR:</strong> Monitoring and performance products (a.k.a APM) proactively gauge
your codebase or API so they can auto-magically highlight errors, crashes and
slow parts that you were missing</p>
<p><strong>Otherwise:</strong> You might spend great effort on measuring API performance and
downtimes, probably you’ll never be aware which are your slowest code parts
under real world scenario and how these affects the UX</p>
<p><strong>Blog quote:</strong> "APM products segments" (From the blog Yoni Goldberg)</p>
<blockquote>
<p>"…APM products constitutes 3 major segments: <strong>1. Website or API monitoring
–</strong> external services that constantly monitor uptime and performance via
HTTP requests. Can be setup in few minutes. Following are few selected
contenders: Pingdom, Uptime Robot, and New Relic <strong>2. Code instrumentation
–</strong> products family which require to embed an agent within the application
to benefit feature slow code detection, exceptions statistics, performance
monitoring and many more. Following are few selected contenders: New Relic,
App Dynamics <strong>3. Operational intelligence dashboard –</strong> these line of
products are focused on facilitating the ops team with metrics and curated
content that helps to easily stay on top of application performance. This is
usually involves aggregating multiple sources of information (application
logs, DB logs, servers log, etc) and upfront dashboard design work.
Following are few selected contenders: Datadog, Splunk"</p>
</blockquote>
<hr>
<p><strong><em>The above is a shortened version - see here more best practices and
examples</em></strong></p>
    </div>
    <aside class="postpromonav"><nav><ul itemprop="keywords" class="tags">
<li><a class="tag p-category" href="../../categories/exception/" rel="tag">exception</a></li>
            <li><a class="tag p-category" href="../../categories/nodejs/" rel="tag">node.js</a></li>
            <li><a class="tag p-category" href="../../categories/serverside-javascript/" rel="tag">serverside-javascript</a></li>
        </ul>
<ul class="pager hidden-print">
<li class="previous">
                <a href="../how-to-get-the-type-of-t-from-a-member-of-a-generic-class-or-method/" rel="prev" title="How to get the type of T from a member of a generic class or method">Previous post</a>
            </li>
            <li class="next">
                <a href="../syntax-for-a-single-line-while-loop-in-bash/" rel="next" title="Syntax for a single-line while loop in Bash">Next post</a>
            </li>
        </ul></nav></aside></article>
</div>
        <!--End of body content-->

        <footer id="footer">
            Contents © 2023         Go to StackOverflow Chinese Site  <a href="http://stackoverflow.ink">StackOverflow中文网</a>  
            
        </footer>
</div>
</div>


            <script src="../../assets/js/all-nocdn.js"></script><!-- fancy dates --><script>
    moment.locale("en");
    fancydates(0, "YYYY-MM-DD HH:mm");
    </script><!-- end fancy dates --><script>
    baguetteBox.run('div#content', {
        ignoreClass: 'islink',
        captions: function(element) {
            return element.getElementsByTagName('img')[0].alt;
    }});
    </script><script src="../../assets/js/search.js"></script>
</body>
</html>
