<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>如何在不停止/退出程序的情况下捕获并打印完整的异常回溯？ | StackOverflow Snapshot</title>
<link href="../../assets/css/all-nocdn.css" rel="stylesheet" type="text/css">
<meta name="theme-color" content="#5670d4">
<meta name="generator" content="Nikola (getnikola.com)">
<link rel="canonical" href="https://ohstackoverflow.netlify.app/posts/ru-he-zai-bu-ting-zhi-tui-chu-cheng-xu-de-qing-kuang-xia-bu-huo-bing-da-yin-wan-zheng-de-yi-chang-hui-su/">
<!--[if lt IE 9]><script src="../../assets/js/html5.js"></script><![endif]--><meta name="author" content="Arya">
<link rel="prev" href="../property-zhuang-shi-qi-zai-python-zhong-ru-he-gong-zuo/" title="@property 装饰器在 Python 中如何工作？" type="text/html">
<link rel="next" href="../b-zi-fu-zai-zi-fu-chuan-wen-zi-qian-mian-zuo-shi-yao/" title="“b”字符在字符串文字前面做什么？" type="text/html">
<meta property="og:site_name" content="StackOverflow Snapshot">
<meta property="og:title" content="如何在不停止/退出程序的情况下捕获并打印完整的异常回溯？">
<meta property="og:url" content="https://ohstackoverflow.netlify.app/posts/ru-he-zai-bu-ting-zhi-tui-chu-cheng-xu-de-qing-kuang-xia-bu-huo-bing-da-yin-wan-zheng-de-yi-chang-hui-su/">
<meta property="og:description" content="我想在不退出的情况下捕获并记录异常，例如，
try:
    do_stuff()
except Exception as err:
    print(Exception, err)
    # I want to print the entire traceback here,
    # not just the exception name and details


我想打印在没有 tr">
<meta property="og:type" content="article">
<meta property="article:published_time" content="2023-02-17T03:36:14+08:00">
<meta property="article:tag" content="exception">
<meta property="article:tag" content="python">
<meta property="article:tag" content="traceback">
<meta property="article:tag" content="try-catch">
</head>
<body>
<a href="#content" class="sr-only sr-only-focusable">Skip to main content</a>

<!-- Menubar -->

<nav class="navbar navbar-inverse navbar-static-top"><div class="container">
<!-- This keeps the margins nice -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar" aria-controls="bs-navbar" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="https://ohstackoverflow.netlify.app/">

                <span id="blog-title">StackOverflow Snapshot</span>
            </a>
        </div>
<!-- /.navbar-header -->
        <div class="collapse navbar-collapse" id="bs-navbar" aria-expanded="false">
            <ul class="nav navbar-nav">
<li>
<a href="../../archive.html">Archive</a>
                </li>
<li>
<a href="../../categories/">Tags</a>

                
            </li>
</ul>
<ul class="nav navbar-nav navbar-right">
<div style="display:table;min-height:5rem;min-width:27rem;">
					<div class="input-group" style="display: table-cell;vertical-align: middle;">
						<input id="words" type="text" class="form-control" style="max-width:22rem;" onkeydown="if(event.keyCode==13){btn.click()}"><span class="input-group-btn" style="float:left">
							<button id="btn" class="btn btn-default" type="button" data-toggle="modal" data-target="#myModal">
								<span class="glyphicon glyphicon-search">
							</span></button>
						</span>
					</div>
<!-- /input-group -->
				</div>

				
                
                
                
            </ul>
</div>
<!-- /.navbar-collapse -->
    </div>
<!-- /.container -->
</nav><!-- End of Menubar --><!-- 模态框（Modal） --><div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×
				</button>
				<h4 class="modal-title" id="myModalLabel">
					查找结果
				</h4>
			</div>
			<div class="modal-body">
				<div id="search-count" style="min-height:4rem;">
				查找中，请稍后...
				</div>
				<div id="search-result">
				</div>

				
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">
					关闭
				</button>
			</div>
		</div>
<!-- /.modal-content -->
	</div>
<!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="container" id="content" role="main">
    <div class="body-content">
        <!--Body content-->
        <div class="row">
            
            
<article class="post-text h-entry hentry postpage" itemscope="itemscope" itemtype="http://schema.org/Article"><header><h1 class="p-name entry-title" itemprop="headline name"><a href="." class="u-url">如何在不停止/退出程序的情况下捕获并打印完整的异常回溯？</a></h1>

        <div class="metadata">
            <p class="byline author vcard p-author h-card"><span class="byline-name fn p-name" itemprop="author">
                    <a class="u-url" href="../../authors/arya/">Arya</a>
            </span></p>
            <p class="dateline">
            <a href="." rel="bookmark">
            <time class="published dt-published" datetime="2023-02-17T03:36:14+08:00" itemprop="datePublished" title="2023-02-17 03:36">2023-02-17 03:36</time></a>
            </p>
            

        </div>
        

    </header><div class="e-content entry-content" itemprop="articleBody text">
    <p>我想在不退出的情况下捕获并记录异常，例如，</p>
<div class="code"><pre class="code literal-block"><span class="k">try</span><span class="o">:</span>
<span class="w">    </span><span class="n">do_stuff</span><span class="o">()</span>
<span class="n">except</span><span class="w"> </span><span class="n">Exception</span><span class="w"> </span><span class="k">as</span><span class="w"> </span><span class="n">err</span><span class="o">:</span>
<span class="w">    </span><span class="n">print</span><span class="o">(</span><span class="n">Exception</span><span class="o">,</span><span class="w"> </span><span class="n">err</span><span class="o">)</span>
<span class="w">    </span><span class="err">#</span><span class="w"> </span><span class="n">I</span><span class="w"> </span><span class="n">want</span><span class="w"> </span><span class="n">to</span><span class="w"> </span><span class="n">print</span><span class="w"> </span><span class="n">the</span><span class="w"> </span><span class="n">entire</span><span class="w"> </span><span class="n">traceback</span><span class="w"> </span><span class="n">here</span><span class="o">,</span>
<span class="w">    </span><span class="err">#</span><span class="w"> </span><span class="n">not</span><span class="w"> </span><span class="n">just</span><span class="w"> </span><span class="n">the</span><span class="w"> </span><span class="n">exception</span><span class="w"> </span><span class="n">name</span><span class="w"> </span><span class="n">and</span><span class="w"> </span><span class="n">details</span>
</pre></div>

<p>我想打印在没有 try/except 拦截异常的情况下引发异常时打印的完全相同的输出，我不 <em>希望</em> 它退出我的程序。</p>
<p><br><br></p>
<h2>解答</h2>
<p>其他一些答案已经指出了回溯模块。</p>
<p>请注意<code>print_exc</code>，在某些极端情况下，您将无法获得预期的结果。在 Python 2.x 中：</p>
<div class="code"><pre class="code literal-block"><span class="kn">import</span> <span class="nn">traceback</span>

<span class="k">try</span><span class="p">:</span>
    <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">"Oups!"</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">Exception</span><span class="p">,</span> <span class="n">err</span><span class="p">:</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">"Again !?!"</span><span class="p">)</span>
    <span class="k">except</span><span class="p">:</span>
        <span class="k">pass</span>

    <span class="n">traceback</span><span class="o">.</span><span class="n">print_exc</span><span class="p">()</span>
</pre></div>

<p><em>...将显示最后一个</em> 异常的回溯：</p>
<div class="code"><pre class="code literal-block">Traceback (most recent call last):
  File "e.py", line 7, in &lt;module&gt;
    raise TypeError("Again !?!")
TypeError: Again !?!
</pre></div>

<p><strong>如果您确实需要访问原始 <em>回溯，</em></strong> 一种解决方案是将返回的
<em>异常信息</em><code>exc_info</code>缓存在局部变量中并使用以下方式显示<code>print_exception</code>：</p>
<div class="code"><pre class="code literal-block"><span class="kn">import</span> <span class="nn">traceback</span>
<span class="kn">import</span> <span class="nn">sys</span>

<span class="k">try</span><span class="p">:</span>
    <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">"Oups!"</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">Exception</span><span class="p">,</span> <span class="n">err</span><span class="p">:</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="n">exc_info</span> <span class="o">=</span> <span class="n">sys</span><span class="o">.</span><span class="n">exc_info</span><span class="p">()</span>

        <span class="c1"># do you usefull stuff here</span>
        <span class="c1"># (potentially raising an exception)</span>
        <span class="k">try</span><span class="p">:</span>
            <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">"Again !?!"</span><span class="p">)</span>
        <span class="k">except</span><span class="p">:</span>
            <span class="k">pass</span>
        <span class="c1"># end of useful stuff</span>


    <span class="k">finally</span><span class="p">:</span>
        <span class="c1"># Display the *original* exception</span>
        <span class="n">traceback</span><span class="o">.</span><span class="n">print_exception</span><span class="p">(</span><span class="o">*</span><span class="n">exc_info</span><span class="p">)</span>
        <span class="k">del</span> <span class="n">exc_info</span>
</pre></div>

<p>生产：</p>
<div class="code"><pre class="code literal-block">Traceback (most recent call last):
  File "t.py", line 6, in &lt;module&gt;
    raise TypeError("Oups!")
TypeError: Oups!
</pre></div>

<p>虽然这有一些陷阱：</p>
<ul>
<li>来自以下文档<code>sys_info</code>：</li>
</ul>
<blockquote>
<p>将回溯返回值分配给正在处理异常的函数中的局部变量将导致 <strong>循环引用</strong> 。这将防止由同一函数中的局部变量或回溯引用的任何内容被垃圾收集。[...]
<strong>如果您确实需要追溯，请确保在使用后将其删除</strong> （最好使用 try ... finally 语句完成）</p>
</blockquote>
<ul>
<li>但是，来自同一个文档：</li>
</ul>
<blockquote>
<p><strong>从 Python 2.2 开始，当启用垃圾收集并且它们变得不可访问时，此类循环会自动回收</strong> ，但避免创建循环仍然更有效。</p>
</blockquote>
<hr>
<p>另一方面，通过允许您访问 <em>与</em> 异常关联的回溯，Python 3 产生了一个不那么令人惊讶的结果：</p>
<div class="code"><pre class="code literal-block"><span class="kn">import</span> <span class="nn">traceback</span>

<span class="k">try</span><span class="p">:</span>
    <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">"Oups!"</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">err</span><span class="p">:</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">"Again !?!"</span><span class="p">)</span>
    <span class="k">except</span><span class="p">:</span>
        <span class="k">pass</span>

    <span class="n">traceback</span><span class="o">.</span><span class="n">print_tb</span><span class="p">(</span><span class="n">err</span><span class="o">.</span><span class="n">__traceback__</span><span class="p">)</span>
</pre></div>

<p>... 将显示：</p>
<div class="code"><pre class="code literal-block">  File "e3.py", line 4, in &lt;module&gt;
    raise TypeError("Oups!")
</pre></div>

<p><br></p>
<h3>更多建议</h3>
<p>其他一些答案已经指出了回溯模块。</p>
<p>请注意<code>print_exc</code>，在某些极端情况下，您将无法获得预期的结果。在 Python 2.x 中：</p>
<div class="code"><pre class="code literal-block"><span class="kn">import</span> <span class="nn">traceback</span>

<span class="k">try</span><span class="p">:</span>
    <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">"Oups!"</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">Exception</span><span class="p">,</span> <span class="n">err</span><span class="p">:</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">"Again !?!"</span><span class="p">)</span>
    <span class="k">except</span><span class="p">:</span>
        <span class="k">pass</span>

    <span class="n">traceback</span><span class="o">.</span><span class="n">print_exc</span><span class="p">()</span>
</pre></div>

<p><em>...将显示最后一个</em> 异常的回溯：</p>
<div class="code"><pre class="code literal-block">Traceback (most recent call last):
  File "e.py", line 7, in &lt;module&gt;
    raise TypeError("Again !?!")
TypeError: Again !?!
</pre></div>

<p><strong>如果您确实需要访问原始 <em>回溯，</em></strong> 一种解决方案是将返回的
<em>异常信息</em><code>exc_info</code>缓存在局部变量中并使用以下方式显示<code>print_exception</code>：</p>
<div class="code"><pre class="code literal-block"><span class="kn">import</span> <span class="nn">traceback</span>
<span class="kn">import</span> <span class="nn">sys</span>

<span class="k">try</span><span class="p">:</span>
    <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">"Oups!"</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">Exception</span><span class="p">,</span> <span class="n">err</span><span class="p">:</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="n">exc_info</span> <span class="o">=</span> <span class="n">sys</span><span class="o">.</span><span class="n">exc_info</span><span class="p">()</span>

        <span class="c1"># do you usefull stuff here</span>
        <span class="c1"># (potentially raising an exception)</span>
        <span class="k">try</span><span class="p">:</span>
            <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">"Again !?!"</span><span class="p">)</span>
        <span class="k">except</span><span class="p">:</span>
            <span class="k">pass</span>
        <span class="c1"># end of useful stuff</span>


    <span class="k">finally</span><span class="p">:</span>
        <span class="c1"># Display the *original* exception</span>
        <span class="n">traceback</span><span class="o">.</span><span class="n">print_exception</span><span class="p">(</span><span class="o">*</span><span class="n">exc_info</span><span class="p">)</span>
        <span class="k">del</span> <span class="n">exc_info</span>
</pre></div>

<p>生产：</p>
<div class="code"><pre class="code literal-block">Traceback (most recent call last):
  File "t.py", line 6, in &lt;module&gt;
    raise TypeError("Oups!")
TypeError: Oups!
</pre></div>

<p>虽然这有一些陷阱：</p>
<ul>
<li>来自以下文档<code>sys_info</code>：</li>
</ul>
<blockquote>
<p>将回溯返回值分配给正在处理异常的函数中的局部变量将导致 <strong>循环引用</strong> 。这将防止由同一函数中的局部变量或回溯引用的任何内容被垃圾收集。[...]
<strong>如果您确实需要追溯，请确保在使用后将其删除</strong> （最好使用 try ... finally 语句完成）</p>
</blockquote>
<ul>
<li>但是，来自同一个文档：</li>
</ul>
<blockquote>
<p><strong>从 Python 2.2 开始，当启用垃圾收集并且它们变得不可访问时，此类循环会自动回收</strong> ，但避免创建循环仍然更有效。</p>
</blockquote>
<hr>
<p>另一方面，通过允许您访问 <em>与</em> 异常关联的回溯，Python 3 产生了一个不那么令人惊讶的结果：</p>
<div class="code"><pre class="code literal-block"><span class="kn">import</span> <span class="nn">traceback</span>

<span class="k">try</span><span class="p">:</span>
    <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">"Oups!"</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">err</span><span class="p">:</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">"Again !?!"</span><span class="p">)</span>
    <span class="k">except</span><span class="p">:</span>
        <span class="k">pass</span>

    <span class="n">traceback</span><span class="o">.</span><span class="n">print_tb</span><span class="p">(</span><span class="n">err</span><span class="o">.</span><span class="n">__traceback__</span><span class="p">)</span>
</pre></div>

<p>... 将显示：</p>
<div class="code"><pre class="code literal-block">  File "e3.py", line 4, in &lt;module&gt;
    raise TypeError("Oups!")
</pre></div>

<p><br><br><a href="../how-to-catch-and-print-the-full-exception-traceback-without-halting-exiting-the-program/">查看原文</a></p>
    </div>
    <aside class="postpromonav"><nav><ul itemprop="keywords" class="tags">
<li><a class="tag p-category" href="../../categories/exception/" rel="tag">exception</a></li>
            <li><a class="tag p-category" href="../../categories/python/" rel="tag">python</a></li>
            <li><a class="tag p-category" href="../../categories/traceback/" rel="tag">traceback</a></li>
            <li><a class="tag p-category" href="../../categories/try-catch/" rel="tag">try-catch</a></li>
        </ul>
<ul class="pager hidden-print">
<li class="previous">
                <a href="../property-zhuang-shi-qi-zai-python-zhong-ru-he-gong-zuo/" rel="prev" title="@property 装饰器在 Python 中如何工作？">Previous post</a>
            </li>
            <li class="next">
                <a href="../b-zi-fu-zai-zi-fu-chuan-wen-zi-qian-mian-zuo-shi-yao/" rel="next" title="“b”字符在字符串文字前面做什么？">Next post</a>
            </li>
        </ul></nav></aside></article>
</div>
        <!--End of body content-->

        <footer id="footer">
            Contents © 2023         Go to StackOverflow Chinese Site  <a href="http://stackoverflow.ink">StackOverflow-ZH</a>  
            
        </footer>
</div>
</div>


            <script src="../../assets/js/all-nocdn.js"></script><!-- fancy dates --><script>
    moment.locale("en");
    fancydates(0, "YYYY-MM-DD HH:mm");
    </script><!-- end fancy dates --><script>
    baguetteBox.run('div#content', {
        ignoreClass: 'islink',
        captions: function(element) {
            return element.getElementsByTagName('img')[0].alt;
    }});
    </script><script src="../../assets/js/search.js"></script>
</body>
</html>
