<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Handling InterruptedException in Java | StackOverflow Snapshot</title>
<link href="../../assets/css/all-nocdn.css" rel="stylesheet" type="text/css">
<meta name="theme-color" content="#5670d4">
<meta name="generator" content="Nikola (getnikola.com)">
<link rel="canonical" href="https://ohstackoverflow.netlify.app/posts/handling-interruptedexception-in-java/">
<!--[if lt IE 9]><script src="../../assets/js/html5.js"></script><![endif]--><meta name="author" content="Arya">
<link rel="prev" href="../how-to-select-from-stored-procedure/" title="How to SELECT FROM stored procedure" type="text/html">
<link rel="next" href="../how-do-i-specify-new-lines-in-a-string-in-order-to-write-multiple-lines-to-a-file/" title="How do I specify new lines in a string in order to write multiple lines to a file?" type="text/html">
<meta property="og:site_name" content="StackOverflow Snapshot">
<meta property="og:title" content="Handling InterruptedException in Java">
<meta property="og:url" content="https://ohstackoverflow.netlify.app/posts/handling-interruptedexception-in-java/">
<meta property="og:description" content="What is the difference between the following ways of handling
InterruptedException? What is the best way to do it?
try{
 //...
} catch(InterruptedException e) { 
   Thread.currentThread().interrupt();">
<meta property="og:type" content="article">
<meta property="article:published_time" content="2023-03-03T15:45:00+08:00">
<meta property="article:tag" content="exception">
<meta property="article:tag" content="interrupted-exception">
<meta property="article:tag" content="java">
<meta property="article:tag" content="multithreading">
</head>
<body>
<a href="#content" class="sr-only sr-only-focusable">Skip to main content</a>

<!-- Menubar -->

<nav class="navbar navbar-inverse navbar-static-top"><div class="container">
<!-- This keeps the margins nice -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar" aria-controls="bs-navbar" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="https://ohstackoverflow.netlify.app/">

                <span id="blog-title">StackOverflow Snapshot</span>
            </a>
        </div>
<!-- /.navbar-header -->
        <div class="collapse navbar-collapse" id="bs-navbar" aria-expanded="false">
            <ul class="nav navbar-nav">
<li>
<a href="../../archive.html">Archive</a>
                </li>
<li>
<a href="../../categories/">Tags</a>

                
            </li>
</ul>
<ul class="nav navbar-nav navbar-right">
<div style="display:table;min-height:5rem;min-width:27rem;">
					<div class="input-group" style="display: table-cell;vertical-align: middle;">
						<input id="words" type="text" class="form-control" style="max-width:22rem;" onkeydown="if(event.keyCode==13){btn.click()}"><span class="input-group-btn" style="float:left">
							<button id="btn" class="btn btn-default" type="button" data-toggle="modal" data-target="#myModal">
								<span class="glyphicon glyphicon-search">
							</span></button>
						</span>
					</div>
<!-- /input-group -->
				</div>

				
                
                
                
            </ul>
</div>
<!-- /.navbar-collapse -->
    </div>
<!-- /.container -->
</nav><!-- End of Menubar --><!-- 模态框（Modal） --><div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×
				</button>
				<h4 class="modal-title" id="myModalLabel">
					查找结果
				</h4>
			</div>
			<div class="modal-body">
				<div id="search-count" style="min-height:4rem;">
				查找中，请稍后...
				</div>
				<div id="search-result">
				</div>

				
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">
					关闭
				</button>
			</div>
		</div>
<!-- /.modal-content -->
	</div>
<!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="container" id="content" role="main">
    <div class="body-content">
        <!--Body content-->
        <div class="row">
            
            
<article class="post-text h-entry hentry postpage" itemscope="itemscope" itemtype="http://schema.org/Article"><header><h1 class="p-name entry-title" itemprop="headline name"><a href="." class="u-url">Handling InterruptedException in Java</a></h1>

        <div class="metadata">
            <p class="byline author vcard p-author h-card"><span class="byline-name fn p-name" itemprop="author">
                    <a class="u-url" href="../../authors/arya/">Arya</a>
            </span></p>
            <p class="dateline">
            <a href="." rel="bookmark">
            <time class="published dt-published" datetime="2023-03-03T15:45:00+08:00" itemprop="datePublished" title="2023-03-03 15:45">2023-03-03 15:45</time></a>
            </p>
            

        </div>
        

    </header><div class="e-content entry-content" itemprop="articleBody text">
    <p>What is the difference between the following ways of handling
<code>InterruptedException</code>? What is the best way to do it?</p>
<div class="code"><pre class="code literal-block">try{
 //...
} catch(InterruptedException e) { 
   Thread.currentThread().interrupt(); 
}
</pre></div>

<p>OR</p>
<div class="code"><pre class="code literal-block">try{
 //...
} catch(InterruptedException e) {
   throw new RuntimeException(e);
}
</pre></div>

<p>EDIT: I'd like to also know in which scenarios are these two used.</p>
<p><br><br></p>
<h2>Answer</h2>
<blockquote>
<p>What is the difference between the following ways of handling
InterruptedException? What is the best way to do it?</p>
</blockquote>
<p>You've probably come to ask this question because you've called a method that
throws <code>InterruptedException</code>.</p>
<p>First of all, you should see <code>throws InterruptedException</code> for what it is: A
part of the method signature and a possible outcome of calling the method
you're calling. So start by embracing the fact that an <code>InterruptedException</code>
is a perfectly valid result of the method call.</p>
<p>Now, if the method you're calling throws such exception, what should <em>your</em>
method do? You can figure out the answer by thinking about the following:</p>
<p><strong>Does it make sense for the method <em>you</em> are implementing to throw an
<code>InterruptedException</code>?</strong> Put differently, is an <code>InterruptedException</code> a
sensible outcome when calling <em>your</em> method?</p>
<ul>
<li>If <strong>yes</strong> , then <code>throws InterruptedException</code> should be part of <em>your</em> method signature, and you should let the exception propagate (i.e. don't catch it at all).</li>
</ul>
<blockquote>
<p><strong>Example</strong> : Your method waits for a value from the network to finish the
computation and return a result. If the blocking network call throws an
<code>InterruptedException</code> your method can not finish computation in a normal
way. You let the <code>InterruptedException</code> propagate.</p>
<div class="code"><pre class="code literal-block"><span class="o">&gt;</span><span class="w">     </span><span class="nv">int</span><span class="w"> </span><span class="nv">computeSum</span><span class="ss">(</span><span class="nv">Server</span><span class="w"> </span><span class="nv">server</span><span class="ss">)</span><span class="w"> </span><span class="nv">throws</span><span class="w"> </span><span class="nv">InterruptedException</span><span class="w"> </span>{
<span class="w">    </span><span class="o">//</span><span class="w"> </span><span class="nv">Any</span><span class="w"> </span><span class="nv">InterruptedException</span><span class="w"> </span><span class="nv">thrown</span><span class="w"> </span><span class="nv">below</span><span class="w"> </span><span class="nv">is</span><span class="w"> </span><span class="nv">propagated</span>
<span class="w">    </span><span class="nv">int</span><span class="w"> </span><span class="nv">a</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="nv">server</span>.<span class="nv">getValueA</span><span class="ss">()</span><span class="c1">;</span>
<span class="w">    </span><span class="nv">int</span><span class="w"> </span><span class="nv">b</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="nv">server</span>.<span class="nv">getValueB</span><span class="ss">()</span><span class="c1">;</span>
<span class="w">    </span><span class="k">return</span><span class="w"> </span><span class="nv">a</span><span class="w"> </span><span class="o">+</span><span class="w"> </span><span class="nv">b</span><span class="c1">;</span>
}
</pre></div>

</blockquote>
<ul>
<li>
<p>If <strong>no</strong> , then you should not declare your method with <code>throws InterruptedException</code> and you should (must!) catch the exception. Now two things are important to keep in mind in this situation:</p>
<ol>
<li>
<p>Someone interrupted your thread. That someone is probably eager to cancel the operation, terminate the program gracefully, or whatever. You should be polite to that someone and return from your method without further ado.</p>
</li>
<li>
<p>Even though <em>your</em> method can manage to produce a sensible return value in case of an <code>InterruptedException</code> the fact that the thread has been interrupted may still be of importance. In particular, the code that calls your method may be interested in whether an interruption occurred during execution of your method. You should therefore log the fact an interruption took place by setting the interrupted flag: <code>Thread.currentThread().interrupt()</code></p>
</li>
</ol>
</li>
</ul>
<blockquote>
<p><strong>Example</strong> : The user has asked to print a sum of two values. Printing
"<code>Failed to compute sum</code>" is acceptable if the sum can't be computed (and
much better than letting the program crash with a stack trace due to an
<code>InterruptedException</code>). In other words, it does <em>not</em> make sense to declare
this method with <code>throws InterruptedException</code>.</p>
<div class="code"><pre class="code literal-block"><span class="o">&gt;</span><span class="w">     </span><span class="nt">void</span><span class="w"> </span><span class="nt">printSum</span><span class="o">(</span><span class="nt">Server</span><span class="w"> </span><span class="nt">server</span><span class="o">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">     </span><span class="err">try</span><span class="w"> </span><span class="err">{</span>
<span class="w">         </span><span class="err">int</span><span class="w"> </span><span class="err">sum</span><span class="w"> </span><span class="err">=</span><span class="w"> </span><span class="err">computeSum(server)</span><span class="p">;</span>
<span class="w">         </span><span class="err">System.out.println("</span><span class="n">Sum</span><span class="p">:</span><span class="w"> </span><span class="s2">" + sum);</span>
<span class="s2">     } catch (InterruptedException e) {</span>
<span class="s2">         Thread.currentThread().interrupt();  // set interrupt flag</span>
<span class="s2">         System.out.println("</span><span class="n">Failed</span><span class="w"> </span><span class="kc">to</span><span class="w"> </span><span class="n">compute</span><span class="w"> </span><span class="n">sum</span><span class="err">"</span><span class="p">);</span>
<span class="w">     </span><span class="p">}</span>
<span class="err">}</span>
</pre></div>

</blockquote>
<p>By now it should be clear that just doing <code>throw new RuntimeException(e)</code> is a
bad idea. It isn't very polite to the caller. You could invent a new runtime
exception but the root cause (someone wants the thread to stop execution)
might get lost.</p>
<p><strong>Other examples:</strong></p>
<blockquote>
<p><strong>Implementing<code>Runnable</code></strong>: As you may have discovered, the signature of
<code>Runnable.run</code> does not allow for rethrowing <code>InterruptedExceptions</code>. Well,
<em>you</em> signed up on implementing <code>Runnable</code>, which means that <em>you</em> signed up
to deal with possible <code>InterruptedExceptions</code>. Either choose a different
interface, such as <code>Callable</code>, or follow the second approach above.</p>
<p><strong>Calling<code>Thread.sleep</code></strong>: You're attempting to read a file and the spec
says you should try 10 times with 1 second in between. You call
<code>Thread.sleep(1000)</code>. So, you need to deal with <code>InterruptedException</code>. For
a method such as <code>tryToReadFile</code> it makes perfect sense to say, <em>"If I'm
interrupted, I can't complete my action of trying to read the file"</em>. In
other words, it makes perfect sense for the method to throw
<code>InterruptedExceptions</code>.</p>
<div class="code"><pre class="code literal-block"><span class="nv">String</span><span class="w"> </span><span class="nv">tryToReadFile</span><span class="ss">(</span><span class="nv">File</span><span class="w"> </span><span class="nv">f</span><span class="ss">)</span><span class="w"> </span><span class="nv">throws</span><span class="w"> </span><span class="nv">InterruptedException</span><span class="w"> </span>{
<span class="w">    </span><span class="k">for</span><span class="w"> </span><span class="ss">(</span><span class="nv">int</span><span class="w"> </span><span class="nv">i</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="mi">0</span><span class="c1">; i &lt; 10; i++) {</span>
<span class="w">        </span><span class="k">if</span><span class="w"> </span><span class="ss">(</span><span class="nv">f</span>.<span class="nv">exists</span><span class="ss">())</span>
<span class="w">            </span><span class="k">return</span><span class="w"> </span><span class="nv">readFile</span><span class="ss">(</span><span class="nv">f</span><span class="ss">)</span><span class="c1">;</span>
<span class="w">        </span><span class="nv">Thread</span>.<span class="nv">sleep</span><span class="ss">(</span><span class="mi">1000</span><span class="ss">)</span><span class="c1">;</span>
<span class="w">    </span>}
<span class="w">    </span><span class="k">return</span><span class="w"> </span><span class="nv">null</span><span class="c1">;</span>
}
</pre></div>

</blockquote>
<hr>
<p>This post has been rewritten as an article here.</p>
<p><br></p>
<h3>Suggest</h3>
<p>As it happens I was just reading about this this morning on my way to work in
Java Concurrency In Practice by Brian Goetz. Basically he says you should do
one of three things</p>
<ol>
<li>
<p><strong>Propagate the<code>InterruptedException</code></strong> - Declare your method to throw the checked <code>InterruptedException</code> so that your caller has to deal with it.</p>
</li>
<li>
<p><strong>Restore the Interrupt</strong> - Sometimes you cannot throw <code>InterruptedException</code>. In these cases you should catch the <code>InterruptedException</code> and restore the interrupt status by calling the <code>interrupt()</code> method on the <code>currentThread</code> so the code higher up the call stack can see that an interrupt was issued, and quickly return from the method. <em>Note: this is only applicable when your method has "try" or "best effort" semantics, i. e. nothing critical would happen if the method doesn't accomplish its goal. For example,<code>log()</code> or <code>sendMetric()</code> may be such method, or <code>boolean tryTransferMoney()</code>, but not <code>void transferMoney()</code>. See here for more details.</em></p>
</li>
<li>
<p><strong>Ignore the interruption within method, but restore the status upon exit</strong> - e. g. via Guava's <code>Uninterruptibles</code>. <code>Uninterruptibles</code> take over the boilerplate code like in the Noncancelable Task example in JCIP § 7.1.3.</p>
</li>
</ol>
</div>
    <aside class="postpromonav"><nav><ul itemprop="keywords" class="tags">
<li><a class="tag p-category" href="../../categories/exception/" rel="tag">exception</a></li>
            <li><a class="tag p-category" href="../../categories/interrupted-exception/" rel="tag">interrupted-exception</a></li>
            <li><a class="tag p-category" href="../../categories/java/" rel="tag">java</a></li>
            <li><a class="tag p-category" href="../../categories/multithreading/" rel="tag">multithreading</a></li>
        </ul>
<ul class="pager hidden-print">
<li class="previous">
                <a href="../how-to-select-from-stored-procedure/" rel="prev" title="How to SELECT FROM stored procedure">Previous post</a>
            </li>
            <li class="next">
                <a href="../how-do-i-specify-new-lines-in-a-string-in-order-to-write-multiple-lines-to-a-file/" rel="next" title="How do I specify new lines in a string in order to write multiple lines to a file?">Next post</a>
            </li>
        </ul></nav></aside></article>
</div>
        <!--End of body content-->

        <footer id="footer">
            Contents © 2023         Go to StackOverflow Chinese Site  <a href="http://stackoverflow.ink">StackOverflow中文网</a>  
            
        </footer>
</div>
</div>


            <script src="../../assets/js/all-nocdn.js"></script><!-- fancy dates --><script>
    moment.locale("en");
    fancydates(0, "YYYY-MM-DD HH:mm");
    </script><!-- end fancy dates --><script>
    baguetteBox.run('div#content', {
        ignoreClass: 'islink',
        captions: function(element) {
            return element.getElementsByTagName('img')[0].alt;
    }});
    </script><script src="../../assets/js/search.js"></script>
</body>
</html>
